# Generated by Django 5.2 on 2026-04-20 21:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments_tenant', '0002_transaction_purpose_processedwebhookevent'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='processedwebhookevent',
            new_name='payments_te_gateway_5a2a61_idx',
            old_name='pwhe_provider_event_idx',
        ),
        migrations.RenameIndex(
            model_name='processedwebhookevent',
            new_name='payments_te_gateway_c22c2d_idx',
            old_name='pwhe_provider_created_idx',
        ),
        migrations.RenameIndex(
            model_name='processedwebhookevent',
            new_name='payments_te_order_n_920172_idx',
            old_name='pwhe_order_number_idx',
        ),
        migrations.AlterField(
            model_name='processedwebhookevent',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
