# Generated by Django 5.2 on 2026-08-25 06:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments_tenant', '0003_rename_pwhe_provider_event_idx_payments_te_gateway_5a2a61_idx_and_more'),
        ('system_pay', '0002_platformpaymentsetting_tenantpaymentsnapshot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantgatewaymode',
            name='gateway',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='tenant_modes', to='system_pay.paymentgatewaydefinition'),
        ),
        migrations.AlterField(
            model_name='tenantgatewaymode',
            name='platform_credential',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='tenant_gateway_modes', to='system_pay.platformgatewaycredential'),
        ),
    ]
