# Generated by Django 5.2 on 2026-04-27 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(help_text='URL-friendly version (auto-generated from title)', max_length=200, unique=True)),
                ('excerpt', models.TextField(blank=True, help_text='Short summary used on blog listings and previews.', max_length=320)),
                ('content', models.TextField(help_text='Post content (supports HTML).')),
                ('featured_image', models.ImageField(blank=True, help_text='Cover image shown on blog cards and post headers.', null=True, upload_to='blog/')),
                ('meta_title', models.CharField(blank=True, help_text='SEO title (defaults to post title).', max_length=70)),
                ('meta_description', models.TextField(blank=True, help_text='SEO description for search results.', max_length=160)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('hidden', 'Hidden')], default='draft', max_length=20)),
                ('is_enabled', models.BooleanField(default=True, help_text='Turn this post on or off without deleting it.')),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'blog_posts',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FAQEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('slug', models.SlugField(help_text='URL-friendly version (auto-generated from the question).', max_length=255, unique=True)),
                ('answer', models.TextField(help_text='FAQ answer content (supports HTML).')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_enabled', models.BooleanField(default=True, help_text='Turn this FAQ on or off without deleting it.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'faq_entries',
                'ordering': ['sort_order', 'question'],
            },
        ),
        migrations.AddField(
            model_name='custompage',
            name='is_enabled',
            field=models.BooleanField(default=True, help_text='Turn this page on or off without deleting its content.'),
        ),
        migrations.AddField(
            model_name='custompage',
            name='page_kind',
            field=models.CharField(choices=[('generic', 'Generic Page'), ('privacy_policy', 'Privacy Policy'), ('terms_of_service', 'Terms & Conditions'), ('cookie_policy', 'Cookie Policy'), ('dmca_policy', 'DMCA Policy'), ('accessibility_statement', 'Accessibility Statement'), ('modern_slavery_statement', 'Modern Slavery Statement'), ('compliance_notice', 'Compliance Notice'), ('cookie_preferences', 'Cookie Preferences'), ('help_center', 'Help Center'), ('delivery_information', 'Delivery Information'), ('returns_policy', 'Returns Policy'), ('warranty_information', 'Warranty Information')], default='generic', help_text='Use generic for normal custom pages, or a managed kind for fixed storefront routes.', max_length=50),
        ),
        migrations.AddIndex(
            model_name='custompage',
            index=models.Index(fields=['page_kind'], name='custom_page_page_ki_6b66f3_idx'),
        ),
        migrations.AddIndex(
            model_name='custompage',
            index=models.Index(fields=['is_enabled'], name='custom_page_is_enab_218b9c_idx'),
        ),
        migrations.AddIndex(
            model_name='blogpost',
            index=models.Index(fields=['slug'], name='blog_posts_slug_b4ca25_idx'),
        ),
        migrations.AddIndex(
            model_name='blogpost',
            index=models.Index(fields=['status'], name='blog_posts_status_795adf_idx'),
        ),
        migrations.AddIndex(
            model_name='blogpost',
            index=models.Index(fields=['is_enabled'], name='blog_posts_is_enab_9dfff2_idx'),
        ),
        migrations.AddIndex(
            model_name='faqentry',
            index=models.Index(fields=['slug'], name='faq_entries_slug_0f217b_idx'),
        ),
        migrations.AddIndex(
            model_name='faqentry',
            index=models.Index(fields=['is_enabled'], name='faq_entries_is_enab_80498d_idx'),
        ),
        migrations.AddIndex(
            model_name='faqentry',
            index=models.Index(fields=['sort_order'], name='faq_entries_sort_or_59a2b4_idx'),
        ),
    ]
