# Generated by Django 5.2 on 2026-04-04 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_5_repair_missing_product_variant_columns'),
    ]


    operations = [
        migrations.AddField(
            model_name='product',
            name='is_pos_available',
            field=models.BooleanField(db_index=True, default=False, help_text='Allow this catalog product to be bridged into the POS catalog.'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='is_pos_available',
            field=models.BooleanField(db_index=True, default=True, help_text='If enabled and the parent product is POS-ready, this variant can be sold in POS.'),
        ),
    ]
