# Generated by Django 5.2 on 2026-05-20 17:10

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_is_pos_available_and_more'),
        ('userauth', '0002_alter_permission_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Date and time when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Date and time when this record was last modified')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Date and time when this record was deleted', null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Whether this record is soft-deleted')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('order_number', models.CharField(blank=True, max_length=50)),
                ('order_item_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('body', models.TextField()),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Moderation'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('flagged', 'Flagged')], db_index=True, default='pending', max_length=16)),
                ('is_verified_purchase', models.BooleanField(db_index=True, default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('moderation_notes', models.TextField(blank=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('helpful_votes', models.PositiveIntegerField(default=0)),
                ('unhelpful_votes', models.PositiveIntegerField(default=0)),
                ('report_count', models.PositiveIntegerField(default=0)),
                ('response_title', models.CharField(blank=True, max_length=255)),
                ('response_body', models.TextField(blank=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to='userauth.tenantuser')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_reviews', to='userauth.customer')),
                ('deleted_by', models.ForeignKey(blank=True, help_text='User who deleted this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to='userauth.tenantuser')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='product.product')),
                ('response_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_review_responses', to='userauth.tenantuser')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last modified this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to='userauth.tenantuser')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_reviews', to='userauth.tenantuser')),
            ],
            options={
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductReviewVote',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Date and time when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Date and time when this record was last modified')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Date and time when this record was deleted', null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Whether this record is soft-deleted')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=255)),
                ('vote_type', models.CharField(choices=[('helpful', 'Helpful'), ('unhelpful', 'Not Helpful')], max_length=16)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to='userauth.tenantuser')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_votes', to='userauth.customer')),
                ('deleted_by', models.ForeignKey(blank=True, help_text='User who deleted this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to='userauth.tenantuser')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='product.productreview')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last modified this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to='userauth.tenantuser')),
            ],
        ),
        migrations.AddIndex(
            model_name='productreview',
            index=models.Index(fields=['product', 'status', 'published_at'], name='product_pro_product_d8a736_idx'),
        ),
        migrations.AddIndex(
            model_name='productreview',
            index=models.Index(fields=['customer', 'status'], name='product_pro_custome_3d2fd0_idx'),
        ),
        migrations.AddIndex(
            model_name='productreview',
            index=models.Index(fields=['rating', 'status'], name='product_pro_rating_3da1cf_idx'),
        ),
        migrations.AddIndex(
            model_name='productreviewvote',
            index=models.Index(fields=['review', 'vote_type'], name='product_pro_review__f89ded_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='productreviewvote',
            unique_together={('review', 'customer'), ('review', 'session_key')},
        ),
    ]
