# Generated by Django 5.2 on 2026-03-26 12:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShopTheme',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('shop_id', models.CharField(db_index=True, max_length=100)),
                ('theme_id', models.UUIDField(db_index=True)),
                ('folder_path', models.CharField(max_length=500)),
                ('is_active', models.BooleanField(db_index=True, default=False)),
                ('is_customized', models.BooleanField(default=False)),
                ('last_customized', models.DateTimeField(blank=True, null=True)),
                ('installed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Shop Theme',
                'verbose_name_plural': 'Shop Themes',
                'db_table': 'shop_themes',
                'indexes': [models.Index(fields=['shop_id', 'is_active'], name='shop_themes_shop_id_91597b_idx')],
                'unique_together': {('shop_id', 'theme_id')},
            },
        ),
        migrations.CreateModel(
            name='ShopThemePage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('page_name', models.CharField(db_index=True, max_length=100)),
                ('file_path', models.CharField(max_length=500)),
                ('css_path', models.CharField(blank=True, max_length=500)),
                ('is_customized', models.BooleanField(default=False)),
                ('original_content_hash', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('shop_theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='theme_manager.shoptheme')),
            ],
            options={
                'verbose_name': 'Shop Theme Page',
                'verbose_name_plural': 'Shop Theme Pages',
                'db_table': 'shop_theme_pages',
                'unique_together': {('shop_theme', 'page_name')},
            },
        ),
    ]
