# Generated by Django 5.2 on 2026-08-28 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='provisioned_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Provisioned At'),
        ),
        migrations.AddField(
            model_name='shop',
            name='provisioning_error',
            field=models.TextField(blank=True, default='', verbose_name='Provisioning Error Trace'),
        ),
        migrations.AddField(
            model_name='shop',
            name='provisioning_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('ready', 'Ready'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20, verbose_name='Provisioning Status'),
        ),
    ]
