# Generated by Django 5.2 on 2026-08-29 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_shop_provisioned_at_shop_provisioning_error_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='provisioning_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('provisioning', 'Provisioning'), ('in_progress', 'In Progress'), ('ready', 'Ready'), ('failed', 'Failed')], db_index=True, default='provisioning', max_length=20, verbose_name='Provisioning Status'),
        ),
    ]
