# Generated by Django 5.2

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_shop_provisioning_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformSmtpSetting',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('host', models.CharField(blank=True, help_text='SMTP server hostname, e.g. smtp.sendgrid.net', max_length=253)),
                ('port', models.PositiveIntegerField(default=587)),
                ('security', models.CharField(choices=[('tls', 'STARTTLS (port 587)'), ('ssl', 'SSL/TLS (port 465)'), ('none', 'None (port 25)')], default='tls', max_length=10)),
                ('username', models.CharField(blank=True, max_length=254)),
                ('password', models.CharField(blank=True, help_text='Stored in plain text — use an app password or API key.', max_length=512)),
                ('default_from_email', models.EmailField(blank=True, max_length=254)),
                ('default_from_name', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=False, help_text='Override Django EMAIL_* settings with these values.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Platform SMTP Setting',
                'verbose_name_plural': 'Platform SMTP Settings',
            },
        ),
        migrations.CreateModel(
            name='PlatformStorageSetting',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('backend', models.CharField(choices=[('local', 'Local Disk (default)'), ('s3', 'AWS S3 / S3-Compatible'), ('vercel', 'Vercel Blob')], default='local', max_length=20)),
                ('s3_access_key_id', models.CharField(blank=True, max_length=128)),
                ('s3_secret_access_key', models.CharField(blank=True, max_length=512)),
                ('s3_bucket_name', models.CharField(blank=True, max_length=63)),
                ('s3_region', models.CharField(blank=True, default='us-east-1', max_length=30)),
                ('s3_endpoint_url', models.CharField(blank=True, help_text='Leave blank for AWS. For DigitalOcean Spaces use https://nyc3.digitaloceanspaces.com', max_length=500)),
                ('s3_custom_domain', models.CharField(blank=True, help_text='Optional CDN/public domain, e.g. cdn.yourplatform.com', max_length=253)),
                ('vercel_blob_read_write_token', models.CharField(blank=True, max_length=512)),
                ('is_active', models.BooleanField(default=False, help_text='Use these settings instead of settings.py STORAGES.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Platform Storage Setting',
                'verbose_name_plural': 'Platform Storage Settings',
            },
        ),
        migrations.CreateModel(
            name='PlatformMessagingSetting',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('none', 'Not configured'), ('twilio', 'Twilio'), ('vonage', 'Vonage (Nexmo)'), ('termii', 'Termii')], default='none', max_length=20)),
                ('twilio_account_sid', models.CharField(blank=True, max_length=64)),
                ('twilio_auth_token', models.CharField(blank=True, max_length=64)),
                ('twilio_from_number', models.CharField(blank=True, help_text='E.164 format: +15005550006', max_length=20)),
                ('twilio_whatsapp_from', models.CharField(blank=True, help_text='WhatsApp sandbox/approved sender, e.g. whatsapp:+14155238886', max_length=30)),
                ('vonage_api_key', models.CharField(blank=True, max_length=32)),
                ('vonage_api_secret', models.CharField(blank=True, max_length=64)),
                ('vonage_from_name', models.CharField(blank=True, help_text='Sender ID (max 11 chars)', max_length=11)),
                ('termii_api_key', models.CharField(blank=True, max_length=128)),
                ('termii_sender_id', models.CharField(blank=True, help_text='Registered sender ID', max_length=11)),
                ('webhook_secret', models.CharField(blank=True, help_text='HMAC secret used to verify inbound provider webhooks.', max_length=64)),
                ('is_active', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Platform Messaging Setting',
                'verbose_name_plural': 'Platform Messaging Settings',
            },
        ),
    ]
