# Generated by Django 5.2 on 2026-03-28 05:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomDomain',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('domain', models.CharField(db_index=True, max_length=253, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Setup'), ('dns_checking', 'Checking DNS'), ('dns_verified', 'DNS Verified'), ('ssl_pending', 'SSL Provisioning'), ('active', 'Active'), ('failed', 'Failed'), ('suspended', 'Suspended'), ('removed', 'Removed')], default='pending', max_length=20)),
                ('is_primary', models.BooleanField(default=False)),
                ('verification_token', models.CharField(editable=False, max_length=64, unique=True)),
                ('verification_method', models.CharField(choices=[('txt', 'TXT Record'), ('cname', 'CNAME Record')], default='txt', max_length=10)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('ssl_status', models.CharField(choices=[('none', 'None'), ('provisioning', 'Provisioning'), ('active', 'Active'), ('expiring_soon', 'Expiring Soon'), ('expired', 'Expired'), ('failed', 'Failed')], default='none', max_length=20)),
                ('ssl_expires_at', models.DateTimeField(blank=True, null=True)),
                ('ssl_provider', models.CharField(default='letsencrypt', max_length=50)),
                ('ssl_cert_path', models.CharField(blank=True, max_length=500)),
                ('ssl_key_path', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_domains', to='core.shop')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ACMEChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=128, unique=True)),
                ('key_auth', models.CharField(max_length=512)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('custom_domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acme_challenges', to='domain.customdomain')),
            ],
        ),
        migrations.CreateModel(
            name='DomainDNSRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_type', models.CharField(choices=[('A', 'A Record'), ('CNAME', 'CNAME Record'), ('TXT', 'TXT Record'), ('AAAA', 'AAAA Record')], max_length=10)),
                ('host', models.CharField(max_length=253)),
                ('value', models.CharField(max_length=512)),
                ('ttl', models.PositiveIntegerField(default=3600)),
                ('purpose', models.CharField(choices=[('routing', 'Routing'), ('verification', 'Verification'), ('ssl', 'SSL')], default='routing', max_length=20)),
                ('is_required', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('custom_domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dns_records', to='domain.customdomain')),
            ],
        ),
        migrations.CreateModel(
            name='DomainEventLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('domain_added', 'Domain Added'), ('verification_started', 'Verification Started'), ('verification_success', 'Verification Success'), ('verification_failed', 'Verification Failed'), ('ssl_requested', 'SSL Requested'), ('ssl_issued', 'SSL Issued'), ('ssl_renewed', 'SSL Renewed'), ('ssl_failed', 'SSL Failed'), ('domain_activated', 'Domain Activated'), ('domain_suspended', 'Domain Suspended'), ('domain_removed', 'Domain Removed'), ('primary_set', 'Set as Primary'), ('nginx_updated', 'Nginx Config Updated')], max_length=30)),
                ('actor', models.CharField(blank=True, max_length=100)),
                ('message', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('custom_domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='domain.customdomain')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DomainHealthCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
                ('dns_resolves', models.BooleanField(default=False)),
                ('ssl_valid', models.BooleanField(default=False)),
                ('http_reachable', models.BooleanField(default=False)),
                ('response_code', models.PositiveIntegerField(blank=True, null=True)),
                ('response_time_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('resolved_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('error_detail', models.TextField(blank=True)),
                ('custom_domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_checks', to='domain.customdomain')),
            ],
            options={
                'ordering': ['-checked_at'],
                'get_latest_by': 'checked_at',
            },
        ),
        migrations.CreateModel(
            name='DomainQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_custom_domains', models.PositiveIntegerField(default=1)),
                ('max_redirects', models.PositiveIntegerField(default=5)),
                ('ssl_auto_provision', models.BooleanField(default=True)),
                ('wildcard_ssl_allowed', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='domain_quota', to='core.shop')),
            ],
        ),
        migrations.CreateModel(
            name='DomainRedirectRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_domain', models.CharField(max_length=253)),
                ('redirect_type', models.CharField(choices=[('301', '301 Permanent'), ('302', '302 Temporary')], default='301', max_length=3)),
                ('is_active', models.BooleanField(default=True)),
                ('preserve_path', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redirect_rules', to='core.shop')),
                ('to_domain', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_redirects', to='domain.customdomain')),
            ],
        ),
        migrations.CreateModel(
            name='DomainResolutionCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(db_index=True, max_length=253, unique=True)),
                ('tenant_id', models.IntegerField()),
                ('tenant_schema', models.CharField(max_length=63)),
                ('domain_type', models.CharField(choices=[('subdomain', 'Subdomain'), ('custom', 'Custom Domain')], max_length=10)),
                ('is_valid', models.BooleanField(default=True)),
                ('cached_at', models.DateTimeField(auto_now=True)),
                ('hit_count', models.PositiveBigIntegerField(default=0)),
            ],
            options={
                'indexes': [models.Index(fields=['hostname', 'is_valid'], name='domain_doma_hostnam_dae993_idx')],
            },
        ),
        migrations.CreateModel(
            name='DomainVerificationAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempted_at', models.DateTimeField(auto_now_add=True)),
                ('result', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('record_missing', 'Record Missing'), ('wrong_value', 'Wrong Value'), ('dns_error', 'DNS Error'), ('timeout', 'Timeout')], max_length=20)),
                ('resolved_value', models.TextField(blank=True)),
                ('expected_value', models.TextField(blank=True)),
                ('error_message', models.TextField(blank=True)),
                ('resolver_used', models.CharField(default='8.8.8.8', max_length=50)),
                ('custom_domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_attempts', to='domain.customdomain')),
            ],
            options={
                'ordering': ['-attempted_at'],
            },
        ),
        migrations.CreateModel(
            name='NginxVhostConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config_content', models.TextField()),
                ('config_hash', models.CharField(max_length=64)),
                ('is_active', models.BooleanField(default=False)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('nginx_reloaded', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('custom_domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nginx_configs', to='domain.customdomain')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SSLCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('provisioning', 'Provisioning'), ('active', 'Active'), ('renewing', 'Renewing'), ('expired', 'Expired'), ('revoked', 'Revoked'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('provider', models.CharField(default='letsencrypt', max_length=50)),
                ('challenge_type', models.CharField(choices=[('http01', 'HTTP-01'), ('dns01', 'DNS-01')], default='http01', max_length=10)),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('auto_renew', models.BooleanField(default=True)),
                ('last_renewed_at', models.DateTimeField(blank=True, null=True)),
                ('cert_fingerprint', models.CharField(blank=True, max_length=128)),
                ('acme_account_id', models.CharField(blank=True, max_length=255)),
                ('cert_path', models.CharField(blank=True, max_length=500)),
                ('key_path', models.CharField(blank=True, max_length=500)),
                ('chain_path', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('custom_domain', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certificate', to='domain.customdomain')),
            ],
        ),
        migrations.CreateModel(
            name='SSLProvisioningLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.CharField(choices=[('initiated', 'Initiated'), ('acme_order', 'ACME Order Created'), ('challenge_created', 'Challenge Created'), ('challenge_placed', 'Challenge Placed'), ('challenge_verify', 'Challenge Verified'), ('cert_issued', 'Certificate Issued'), ('nginx_reloaded', 'Nginx Reloaded'), ('completed', 'Completed'), ('failed', 'Failed')], max_length=30)),
                ('success', models.BooleanField(default=True)),
                ('message', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('certificate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='domain.sslcertificate')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='customdomain',
            index=models.Index(fields=['domain', 'status'], name='domain_cust_domain_f39ff3_idx'),
        ),
        migrations.AddIndex(
            model_name='customdomain',
            index=models.Index(fields=['tenant', 'status'], name='domain_cust_tenant__eed37c_idx'),
        ),
        migrations.AddIndex(
            model_name='acmechallenge',
            index=models.Index(fields=['token', 'is_active'], name='domain_acme_token_06b596_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='domainredirectrule',
            unique_together={('tenant', 'from_domain')},
        ),
    ]
