# Generated by Django 5.2 on 2026-04-04 15:22

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('system_feature_marketplace', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureEntitlementIndex',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('schema_name', models.CharField(db_index=True, max_length=63)),
                ('entitlement_id', models.UUIDField(db_index=True, unique=True)),
                ('feature_id', models.UUIDField(db_index=True)),
                ('feature_code', models.CharField(db_index=True, max_length=100)),
                ('feature_name', models.CharField(blank=True, max_length=150)),
                ('feature_type', models.CharField(db_index=True, max_length=20)),
                ('status', models.CharField(blank=True, db_index=True, max_length=20)),
                ('source', models.CharField(blank=True, max_length=20)),
                ('purchase_reference', models.CharField(blank=True, db_index=True, max_length=64)),
                ('quantity_granted', models.PositiveIntegerField(default=0)),
                ('quantity_used', models.PositiveIntegerField(default=0)),
                ('boolean_value', models.BooleanField(default=False)),
                ('limit_value', models.PositiveIntegerField(default=0)),
                ('billing_cycle', models.CharField(blank=True, max_length=20)),
                ('currency', models.CharField(default='NGN', max_length=3)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('usage_summary', models.CharField(blank=True, max_length=255)),
                ('last_synced_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_entitlement_indices', to='core.shop')),
            ],
            options={
                'ordering': ['feature_name', 'schema_name', '-created_at'],
                'indexes': [models.Index(fields=['feature_code', 'schema_name'], name='system_feat_feature_737438_idx'), models.Index(fields=['schema_name', 'status'], name='system_feat_schema__2cba8e_idx')],
            },
        ),
        migrations.CreateModel(
            name='TenantFeatureOverride',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('schema_name', models.CharField(db_index=True, max_length=63)),
                ('mode', models.CharField(choices=[('force_enabled', 'Force Enabled'), ('force_disabled', 'Force Disabled'), ('free', 'Free'), ('custom_price', 'Custom Price'), ('custom_discount_percent', 'Custom Discount (%)'), ('custom_discount_amount', 'Custom Discount Amount')], db_index=True, max_length=30)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('currency', models.CharField(blank=True, max_length=3)),
                ('billing_cycle', models.CharField(blank=True, choices=[('one_time', 'One-Time'), ('monthly', 'Monthly'), ('annual', 'Annual'), ('perpetual', 'Perpetual')], max_length=20)),
                ('custom_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('custom_discount_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('custom_discount_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('effective_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('effective_until', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_overrides', to='system_feature_marketplace.featuredefinition')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_overrides', to='core.shop')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['schema_name', 'is_active'], name='system_feat_schema__4d1290_idx'), models.Index(fields=['feature', 'is_active'], name='system_feat_feature_6529ee_idx')],
            },
        ),
    ]
