"""
Django settings for sabistart project.

Generated by 'django-admin startproject' using Django 5.2.
"""

import os
import sys
from pathlib import Path
from urllib.parse import urlparse

from django.core.exceptions import ImproperlyConfigured

try:
    import dj_database_url
except Exception:  # pragma: no cover - optional dependency until installed
    dj_database_url = None


BASE_DIR = Path(__file__).resolve().parent.parent
THEMES_ROOT = BASE_DIR / "themes"
IS_VERCEL = bool(os.getenv("VERCEL")) or bool(os.getenv("VERCEL_URL"))
IS_RENDER = bool(os.getenv("RENDER"))


def env(name: str, default=None):
    return os.getenv(name, default)


def env_bool(name: str, default: bool = False) -> bool:
    raw_value = os.getenv(name)
    if raw_value is None:
        return default
    return raw_value.strip().lower() in {"1", "true", "yes", "on"}


def env_int(name: str, default: int) -> int:
    raw_value = os.getenv(name)
    if raw_value is None or raw_value == "":
        return default
    try:
        return int(raw_value)
    except ValueError as exc:
        raise ImproperlyConfigured(
            f"Environment variable {name} must be an integer.") from exc


def env_list(name: str, default=None):
    raw_value = os.getenv(name)
    if raw_value is None:
        return list(default or [])
    return [item.strip() for item in raw_value.split(",") if item.strip()]


def env_path(name: str, default: Path) -> Path:
    raw_value = os.getenv(name)
    if not raw_value:
        return default
    return Path(raw_value).expanduser()


def env_first(*names: str, default=None):
    for name in names:
        raw_value = os.getenv(name)
        if raw_value is not None and raw_value != "":
            return raw_value
    return default


def _active_management_command() -> str:
    return sys.argv[1] if len(sys.argv) > 1 else ""


def _is_migration_command() -> bool:
    return _active_management_command() in {
        "migrate",
        "migrate_schemas",
        "showmigrations",
        "sqlmigrate",
    }


def _is_neon_pooler_url(database_url: str) -> bool:
    if not database_url:
        return False
    try:
        hostname = (urlparse(database_url).hostname or "").lower()
    except Exception:
        return False
    return "-pooler." in hostname and ".neon.tech" in hostname


def _discover_theme_static_dirs():
    static_dirs = []
    if not THEMES_ROOT.exists():
        return static_dirs
    for theme_dir in sorted(THEMES_ROOT.iterdir()):
        candidate = theme_dir / "static"
        if theme_dir.is_dir() and candidate.exists():
            static_dirs.append(candidate)
    return static_dirs


DEFAULT_SECRET_KEY = "django-insecure-(g49vd#cf5e$0r748s)nd8trwnm7mu9rh@2mw-&a2&+)0d#t6^"
SECRET_KEY = env("DJANGO_SECRET_KEY", DEFAULT_SECRET_KEY)
DEBUG = env_bool("DJANGO_DEBUG", default=not IS_VERCEL)
ALLOWED_HOSTS = env_list("DJANGO_ALLOWED_HOSTS")
if ALLOWED_HOSTS:
    ALLOWED_HOSTS = ALLOWED_HOSTS
elif DEBUG:
    ALLOWED_HOSTS = ["*"]
else:
    ALLOWED_HOSTS = ["localhost", "127.0.0.1", "[::1]"]

for host in (env("VERCEL_URL", "").strip(), env("PUBLIC_VERCEL_URL", "").strip()):
    if host and host not in ALLOWED_HOSTS:
        ALLOWED_HOSTS.append(host)
if IS_VERCEL and ".vercel.app" not in ALLOWED_HOSTS:
    ALLOWED_HOSTS.append(".vercel.app")

if not DEBUG and SECRET_KEY == DEFAULT_SECRET_KEY:
    raise ImproperlyConfigured(
        "Set DJANGO_SECRET_KEY before running in production.")

CSRF_TRUSTED_ORIGINS = env_list("DJANGO_CSRF_TRUSTED_ORIGINS")
for host in (env("VERCEL_URL", "").strip(), env("PUBLIC_VERCEL_URL", "").strip()):
    if host:
        origin = f"https://{host}"
        if origin not in CSRF_TRUSTED_ORIGINS:
            CSRF_TRUSTED_ORIGINS.append(origin)


SHARED_APPS = (
    "django_tenants",
    "django.contrib.admin",
    "django.contrib.contenttypes",
    "django.contrib.auth",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "system.core",
    "system.account",
    "system.system_pay",
    "system.feature_marketplace.apps.FeatureMarketplaceConfig",
    "system.theme_marketplace",
    "public.monitoring",
    "dashboard.domain",
)

TENANT_APPS = (
    "django.contrib.admin",
    "django.contrib.contenttypes",
    "django.contrib.auth",
    "django.contrib.sessions",
    "django.contrib.messages",
    "public.userauth",
    "public.home",
    # "public.store_settings",
    "public.category",
    "public.product",
    "public.cart",
    "public.search",
    "public.checkout",
    "public.promotions",
    "public.content",
    "public.shipping",
    "public.support",
    "public.legal",
    "public.i18n",
    "public.b2b",
    "public.monitoring",
    "dashboard.store_settings",
    # "dashboard.settings",
    "dashboard.categories_settings",
    "dashboard.pricing",
    "dashboard.notification",
    "dashboard.product_settings",
    "dashboard.theme_manager",
    "dashboard.pos",
    "dashboard.payments_tenant",
    "dashboard.feature_marketplace",
    "dashboard.monitoring",
)

INSTALLED_APPS = list(SHARED_APPS) + [
    app for app in TENANT_APPS if app not in SHARED_APPS
]

TENANT_MODEL = "core.Shop"
TENANT_DOMAIN_MODEL = "core.Domain"
TENANT_COLOR_ADMIN_APPS = False


AUTH_USER_MODEL = "account.PlatformUser"
AUTHENTICATION_BACKENDS = [
    "sabistart.auth_backends.SchemaAwareAuthenticationBackend",
]


ROOT_URLCONF = "sabistart.urls"
PUBLIC_SCHEMA_URLCONF = "sabistart.urls_public"

MIDDLEWARE = [
    "dashboard.domain.middleware.CustomDomainMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "public.monitoring.middleware.VisitorMonitoringMiddleware",
    # "dashboard.settings.middleware.CurrentUserMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [
            BASE_DIR / "templates",
        ],
        "APP_DIRS": False,
        "OPTIONS": {
            "loaders": [
                "themes.loader.Loader",
                "django.template.loaders.filesystem.Loader",
                "django.template.loaders.app_directories.Loader",
            ],
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "django.template.context_processors.media",
                "public.storefront.context_processors.global_storefront_context",
            ],
        },
    },
]

WSGI_APPLICATION = "sabistart.wsgi.application"

DATABASE_ROUTERS = (
    "django_tenants.routers.TenantSyncRouter",
)

pooled_database_url = env("DATABASE_URL") or env(
    "POSTGRES_URL") or env("POSTGRES_PRISMA_URL")
unpooled_database_url = env(
    "DATABASE_URL_UNPOOLED") or env("DATABASE_URL_DIRECT")

if _is_migration_command() and unpooled_database_url:
    database_url = unpooled_database_url
else:
    database_url = pooled_database_url

if _is_migration_command() and _is_neon_pooler_url(database_url) and not unpooled_database_url:
    raise ImproperlyConfigured(
        "You are running a migration command with a Neon pooled connection string "
        "(`-pooler` host). For this project, use a direct Neon connection for migrations. "
        "Set DATABASE_URL_UNPOOLED (or DATABASE_URL_DIRECT) to the direct Neon URL."
    )

if database_url:
    if dj_database_url is None:
        raise ImproperlyConfigured(
            "Install dj-database-url to use DATABASE_URL or POSTGRES_URL based configuration.")
    DATABASES = {
        "default": dj_database_url.parse(
            database_url,
            conn_max_age=env_int("DB_CONN_MAX_AGE", 60 if not DEBUG else 0),
        )
    }
    DATABASES["default"]["ENGINE"] = "django_tenants.postgresql_backend"
    DATABASES["default"].setdefault("OPTIONS", {})
else:
    DATABASES = {
        "default": {
            "ENGINE": env("DB_ENGINE", "django_tenants.postgresql_backend"),
            "NAME": env("DB_NAME", "sabistore"),
            "USER": env("DB_USER", "sabistore"),
            "PASSWORD": env("DB_PASSWORD", "sabistore"),
            "HOST": env("DB_HOST", "localhost"),
            "PORT": env("DB_PORT", "5432"),
            "CONN_MAX_AGE": env_int("DB_CONN_MAX_AGE", 60 if not DEBUG else 0),
            "OPTIONS": {},
        }
    }

db_ssl_mode = env("DB_SSLMODE", "")
if db_ssl_mode:
    DATABASES["default"]["OPTIONS"]["sslmode"] = db_ssl_mode

if DATABASES["default"]["ENGINE"] != "django_tenants.postgresql_backend":
    raise ImproperlyConfigured(
        "This project requires the django-tenants PostgreSQL backend.")

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


LANGUAGE_CODE = env("DJANGO_LANGUAGE_CODE", "en-us")
TIME_ZONE = env("DJANGO_TIME_ZONE", "UTC")
USE_I18N = True
USE_TZ = True


STATIC_ROOT = env_path("DJANGO_STATIC_ROOT", BASE_DIR / "staticfiles")
STATIC_URL = env("DJANGO_STATIC_URL", "/static/")
STATICFILES_DIRS = [BASE_DIR / "static", * _discover_theme_static_dirs()]
MULTITENANT_RELATIVE_STATIC_ROOT = "%s"

REWRITE_STATIC_URLS = True
WHITENOISE_AUTOREFRESH = DEBUG
WHITENOISE_USE_FINDERS = DEBUG

MEDIA_ROOT = env_path("DJANGO_MEDIA_ROOT", Path(
    "/tmp/sabistart-media") if IS_VERCEL else BASE_DIR / "media")
MEDIA_URL = env("DJANGO_MEDIA_URL", "/media/")

default_storage_backend = env("DJANGO_DEFAULT_FILE_STORAGE", "")
if not default_storage_backend:
    if IS_VERCEL:
        default_storage_backend = "sabistart.storage_backends.VercelBlobStorage"
    else:
        default_storage_backend = "django_tenants.files.storage.TenantFileSystemStorage"

if (
    IS_VERCEL
    and default_storage_backend == "sabistart.storage_backends.VercelBlobStorage"
    and not env("BLOB_READ_WRITE_TOKEN")
):
    raise ImproperlyConfigured(
        "BLOB_READ_WRITE_TOKEN is required when using Vercel Blob storage on Vercel.")

STORAGES = {
    "default": {
        "BACKEND": default_storage_backend,
    },
    "staticfiles": {
        "BACKEND": "django_tenants.staticfiles.storage.TenantStaticFilesStorage",
    },
}

MULTITENANT_RELATIVE_MEDIA_ROOT = "tenants/%s"
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

DASHBOARD_PREFIX = "admin"

SERVER_IP = env("SERVER_IP", "127.0.0.1")
configured_platform_cname = env("PLATFORM_CNAME", "")
if IS_VERCEL and configured_platform_cname.strip().lower() in {"", "localhost", "127.0.0.1"}:
    PLATFORM_CNAME = env_first(
        "PUBLIC_VERCEL_URL",
        "VERCEL_URL",
        default="localhost",
    )
else:
    PLATFORM_CNAME = configured_platform_cname or "localhost"
SUBDOMAIN_SUFFIX = env("SUBDOMAIN_SUFFIX", "")
DOMAIN_RESOLUTION_CACHE_TTL = env_int("DOMAIN_RESOLUTION_CACHE_TTL", 300)
DOMAIN_SIMULATE_INFRA = env_bool(
    "DOMAIN_SIMULATE_INFRA", default=DEBUG and not IS_VERCEL)
DEFAULT_TENANT_SCHEMA = env("DEFAULT_TENANT_SCHEMA", "sho")

USE_X_FORWARDED_HOST = env_bool(
    "DJANGO_USE_X_FORWARDED_HOST", default=not DEBUG)
USE_X_FORWARDED_PORT = env_bool(
    "DJANGO_USE_X_FORWARDED_PORT", default=not DEBUG)
if env_bool("DJANGO_TRUST_X_FORWARDED_PROTO", default=not DEBUG):
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

SECURE_SSL_REDIRECT = env_bool("DJANGO_SECURE_SSL_REDIRECT", default=not DEBUG)
SESSION_COOKIE_SECURE = env_bool(
    "DJANGO_SESSION_COOKIE_SECURE", default=not DEBUG)
CSRF_COOKIE_SECURE = env_bool("DJANGO_CSRF_COOKIE_SECURE", default=not DEBUG)
SECURE_HSTS_SECONDS = env_int(
    "DJANGO_SECURE_HSTS_SECONDS", 31536000 if not DEBUG else 0)
SECURE_HSTS_INCLUDE_SUBDOMAINS = env_bool(
    "DJANGO_SECURE_HSTS_INCLUDE_SUBDOMAINS", default=not DEBUG)
SECURE_HSTS_PRELOAD = env_bool("DJANGO_SECURE_HSTS_PRELOAD", default=not DEBUG)
SECURE_CONTENT_TYPE_NOSNIFF = env_bool(
    "DJANGO_SECURE_CONTENT_TYPE_NOSNIFF", default=True)
SECURE_REFERRER_POLICY = env("DJANGO_SECURE_REFERRER_POLICY", "same-origin")
X_FRAME_OPTIONS = env("DJANGO_X_FRAME_OPTIONS", "SAMEORIGIN")

DEFAULT_FROM_EMAIL = env("DJANGO_DEFAULT_FROM_EMAIL", "no-reply@localhost")
SERVER_EMAIL = env("DJANGO_SERVER_EMAIL", DEFAULT_FROM_EMAIL)

log_to_file = env_bool("DJANGO_LOG_TO_FILE", default=not IS_VERCEL)
LOG_TO_FILE = log_to_file
LOG_DIR = env_path("DJANGO_LOG_DIR", Path("/tmp/logs")
                   if (IS_VERCEL or IS_RENDER) else BASE_DIR / "logs")

log_handlers = ["console"]
handlers = {
    "console": {
        "class": "logging.StreamHandler",
        "formatter": "standard",
    },
}
if log_to_file:
    # Create logs directory only when file logging is enabled and defer creation until runtime
    try:
        LOG_DIR.mkdir(parents=True, exist_ok=True)
        handlers["file"] = {
            "class": "logging.FileHandler",
            "filename": str(LOG_DIR / "django.log"),
            "formatter": "standard",
        }
        log_handlers.append("file")
    except (OSError, IOError):
        # If we can't create the log directory (e.g., read-only filesystem), fall back to console only
        print("Warning: Could not create log directory. Logging to console only.")
        pass

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "standard": {
            "format": "%(levelname)s %(asctime)s %(name)s %(message)s",
        },
    },
    "handlers": handlers,
    "root": {
        "handlers": log_handlers,
        "level": env("DJANGO_LOG_LEVEL", "INFO"),
    },
}
