# Generated by Django 5.2 on 2026-03-26 12:35

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Stable UUID — safe to expose in URLs.', primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, help_text='Primary login identifier. Must be unique across the platform.', max_length=254, unique=True, verbose_name='email address')),
                ('first_name', models.CharField(blank=True, max_length=100, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=100, verbose_name='last name')),
                ('phone', models.CharField(blank=True, max_length=30, validators=[django.core.validators.RegexValidator('^\\+?1?\\d{9,15}$', 'Enter a valid international phone number (e.g. +2348012345678).')], verbose_name='phone number')),
                ('avatar_url', models.URLField(blank=True, verbose_name='avatar URL')),
                ('account_status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive — login disabled'), ('SUSPENDED', 'Suspended — platform action'), ('PENDING', 'Pending — email not verified'), ('DELETED', 'Soft-deleted — GDPR anonymised')], db_index=True, default='PENDING', max_length=12, verbose_name='account status')),
                ('is_verified', models.BooleanField(default=False, help_text='Email address has been verified via token.', verbose_name='email verified')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='verified at')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into the Django admin site.', verbose_name='staff status')),
                ('is_platform_admin', models.BooleanField(default=False, help_text='Full platform administrator — can act on any tenant for support purposes.', verbose_name='platform admin')),
                ('totp_secret', models.CharField(blank=True, help_text='Base32-encoded TOTP secret. Encrypted at rest.', max_length=64, verbose_name='TOTP secret')),
                ('totp_enabled', models.BooleanField(default=False, verbose_name='TOTP enabled')),
                ('totp_confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='TOTP confirmed at')),
                ('backup_codes_enc', models.TextField(blank=True, help_text='Encrypted JSON list of hashed one-time backup codes.', verbose_name='backup codes')),
                ('google_id', models.CharField(blank=True, db_index=True, max_length=200)),
                ('facebook_id', models.CharField(blank=True, db_index=True, max_length=200)),
                ('github_id', models.CharField(blank=True, db_index=True, max_length=200)),
                ('locale', models.CharField(default='en', help_text='Preferred language/locale code, e.g. en, fr, ar.', max_length=10, verbose_name='locale')),
                ('timezone', models.CharField(default='UTC', max_length=50, verbose_name='timezone')),
                ('email_marketing', models.BooleanField(default=True, help_text='Consent to receive platform marketing emails.', verbose_name='email marketing consent')),
                ('last_login_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='last login IP')),
                ('last_login_at', models.DateTimeField(blank=True, null=True, verbose_name='last login at')),
                ('failed_login_count', models.PositiveSmallIntegerField(default=0, verbose_name='failed login count')),
                ('locked_until', models.DateTimeField(blank=True, help_text='Account locked after too many failed login attempts.', null=True, verbose_name='locked until')),
                ('force_password_reset', models.BooleanField(default=False, help_text='User must change password on next login.', verbose_name='force password reset')),
                ('password_changed_at', models.DateTimeField(blank=True, null=True, verbose_name='password changed at')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted at')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Arbitrary extra data for integrations, feature flags, etc.', verbose_name='metadata')),
                ('groups', models.ManyToManyField(blank=True, related_name='platform_users', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='platform_users', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Platform User',
                'verbose_name_plural': 'Platform Users',
                'db_table': 'platform_users',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlatformAPIKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Human-readable label, e.g. 'Production Server Key'.", max_length=100)),
                ('key_type', models.CharField(choices=[('PUBLIC', 'Public key — client-side safe'), ('SECRET', 'Secret key — server-side only'), ('WEBHOOK', 'Webhook signing secret')], default='SECRET', max_length=10)),
                ('key_hash', models.CharField(db_index=True, help_text='SHA-256 hash of the raw key. Never store the raw key.', max_length=64, unique=True)),
                ('key_prefix', models.CharField(help_text='First 8 chars of the raw key for display/identification.', max_length=12)),
                ('scopes', models.JSONField(default=list, help_text="List of permission scopes, e.g. ['shops:read', 'billing:write'].")),
                ('ip_allowlist', models.JSONField(blank=True, default=list, help_text='Optional list of allowed IP addresses/CIDRs. Empty = allow all.')),
                ('is_active', models.BooleanField(default=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('last_used_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'platform_api_keys',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlatformEmailVerificationToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(db_index=True, help_text='URL-safe 64-byte random token.', max_length=128, unique=True)),
                ('purpose', models.CharField(choices=[('VERIFY_EMAIL', 'Initial email verification'), ('CHANGE_EMAIL', 'Verify new email after change'), ('REACTIVATE', 'Reactivate a suspended account')], default='VERIFY_EMAIL', max_length=20)),
                ('new_email', models.EmailField(blank=True, help_text='For CHANGE_EMAIL — the new email being verified.', max_length=254)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('is_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_verification_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'platform_email_verification_tokens',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlatformLoginAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('attempted_email', models.EmailField(help_text='Email address used in the login attempt.', max_length=254)),
                ('result', models.CharField(choices=[('SUCCESS', 'Successful login'), ('FAILED_CREDS', 'Wrong email or password'), ('FAILED_2FA', '2FA verification failed'), ('LOCKED', 'Account locked'), ('SUSPENDED', 'Account suspended'), ('OAUTH_SUCCESS', 'OAuth login successful'), ('OAUTH_FAILED', 'OAuth login failed')], max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('country', models.CharField(blank=True, max_length=2)),
                ('is_suspicious', models.BooleanField(default=False, help_text='Flagged by risk engine (new country, impossible travel, etc.).')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='login_audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'platform_login_audit_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlatformPasswordResetToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(db_index=True, max_length=128, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('is_used', models.BooleanField(default=False)),
                ('request_ip', models.GenericIPAddressField(blank=True, help_text='IP address that requested the reset.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'platform_password_reset_tokens',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='platformuser',
            index=models.Index(fields=['email'], name='platform_user_email_idx'),
        ),
        migrations.AddIndex(
            model_name='platformuser',
            index=models.Index(fields=['account_status'], name='platform_user_status_idx'),
        ),
        migrations.AddIndex(
            model_name='platformuser',
            index=models.Index(fields=['created_at'], name='platform_user_created_idx'),
        ),
        migrations.AddIndex(
            model_name='platformuser',
            index=models.Index(fields=['google_id'], name='platform_user_google_idx'),
        ),
        migrations.AddIndex(
            model_name='platformuser',
            index=models.Index(fields=['facebook_id'], name='platform_user_fb_idx'),
        ),
        migrations.AddIndex(
            model_name='platformapikey',
            index=models.Index(fields=['key_hash'], name='platform_apikey_hash_idx'),
        ),
        migrations.AddIndex(
            model_name='platformapikey',
            index=models.Index(fields=['user', 'is_active'], name='platform_apikey_user_idx'),
        ),
        migrations.AddIndex(
            model_name='platformemailverificationtoken',
            index=models.Index(fields=['token'], name='platform_evt_token_idx'),
        ),
        migrations.AddIndex(
            model_name='platformemailverificationtoken',
            index=models.Index(fields=['user', 'purpose', 'is_used'], name='platform_evt_user_purpose_idx'),
        ),
        migrations.AddIndex(
            model_name='platformloginauditlog',
            index=models.Index(fields=['user', 'created_at'], name='platform_audit_user_idx'),
        ),
        migrations.AddIndex(
            model_name='platformloginauditlog',
            index=models.Index(fields=['ip_address'], name='platform_audit_ip_idx'),
        ),
        migrations.AddIndex(
            model_name='platformloginauditlog',
            index=models.Index(fields=['is_suspicious'], name='platform_audit_suspicious_idx'),
        ),
        migrations.AddIndex(
            model_name='platformpasswordresettoken',
            index=models.Index(fields=['token'], name='platform_prt_token_idx'),
        ),
        migrations.AddIndex(
            model_name='platformpasswordresettoken',
            index=models.Index(fields=['user', 'is_used'], name='platform_prt_user_idx'),
        ),
    ]
