# Generated by Django 5.2 on 2026-04-14 15:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnboardingSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('business_name', models.CharField(blank=True, max_length=120)),
                ('desired_subdomain', models.SlugField(blank=True, max_length=63)),
                ('selected_bundle_slug', models.SlugField(blank=True, max_length=100)),
                ('selected_feature_codes', models.JSONField(blank=True, default=list)),
                ('selected_theme_slug', models.SlugField(blank=True, max_length=100)),
                ('currency', models.CharField(default='NGN', max_length=3)),
                ('estimated_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('ready', 'Ready'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=20)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('skipped', 'Skipped'), ('paid', 'Paid'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'platform_onboarding_sessions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['session_token'], name='platform_onboarding_token_idx'), models.Index(fields=['status', 'payment_status'], name='platform_onboarding_status_idx')],
            },
        ),
    ]
