# Generated by Django 5.2 on 2026-03-26 12:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Date and time when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Date and time when this record was last modified')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Date and time when this record was deleted', null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Whether this record is soft-deleted')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('story', models.TextField(blank=True, help_text='Brand story/about')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='brands/%Y/%m/')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='brands/banners/%Y/%m/')),
                ('website', models.URLField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('facebook', models.URLField(blank=True)),
                ('twitter', models.URLField(blank=True)),
                ('instagram', models.URLField(blank=True)),
                ('youtube', models.URLField(blank=True)),
                ('meta_title', models.CharField(blank=True, max_length=255)),
                ('meta_description', models.TextField(blank=True, max_length=500)),
                ('meta_keywords', models.TextField(blank=True)),
                ('featured', models.BooleanField(db_index=True, default=False)),
                ('display_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Date and time when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Date and time when this record was last modified')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Date and time when this record was deleted', null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Whether this record is soft-deleted')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/%Y/%m/')),
                ('icon', models.CharField(blank=True, help_text='CSS icon class or emoji', max_length=100)),
                ('meta_title', models.CharField(blank=True, max_length=255)),
                ('meta_description', models.TextField(blank=True, max_length=500)),
                ('meta_keywords', models.TextField(blank=True)),
                ('canonical_url', models.URLField(blank=True)),
                ('display_order', models.IntegerField(db_index=True, default=0)),
                ('featured', models.BooleanField(db_index=True, default=False)),
                ('show_in_menu', models.BooleanField(default=True)),
                ('menu_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_visible', models.BooleanField(default=True)),
                ('view_count', models.PositiveBigIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Date and time when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Date and time when this record was last modified')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Date and time when this record was deleted', null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Whether this record is soft-deleted')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('color', models.CharField(default='#000000', max_length=7)),
                ('icon', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('meta_title', models.CharField(blank=True, max_length=255)),
                ('meta_description', models.TextField(blank=True, max_length=500)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
