import uuid
from decimal import Decimal

from django.db import models
from django.utils import timezone
from django.utils.translation import gettext_lazy as _

from .core import AppendOnlyModel, TenantPaymentProfile, TimestampedModel


class ReconciliationReport(TimestampedModel):
    class ReportStatus(models.TextChoices):
        PENDING = "pending", _("Pending Review")
        MATCHED = "matched", _("Matched - Clean")
        DISCREPANCY = "discrepancy", _("Discrepancy Detected")
        RESOLVED = "resolved", _("Discrepancy Resolved")
        ERROR = "error", _("Report Generation Error")

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    payment_profile = models.ForeignKey(
        TenantPaymentProfile,
        on_delete=models.CASCADE,
        related_name="reconciliation_reports",
    )
    report_date = models.DateField(_("Report Date"), db_index=True)
    gateway_provider = models.CharField(_("Gateway Provider"), max_length=20)
    currency = models.CharField(_("Currency"), max_length=3)
    status = models.CharField(
        _("Status"),
        max_length=15,
        choices=ReportStatus.choices,
        default=ReportStatus.PENDING,
        db_index=True,
    )

    platform_transaction_count = models.PositiveIntegerField(_("Platform Transaction Count"), default=0)
    platform_gross_amount = models.DecimalField(_("Platform Gross"), max_digits=18, decimal_places=2, default=Decimal("0.00"))
    platform_commission_earned = models.DecimalField(_("Platform Commission"), max_digits=18, decimal_places=2, default=Decimal("0.00"))
    platform_gateway_fees = models.DecimalField(_("Platform Gateway Fees"), max_digits=18, decimal_places=2, default=Decimal("0.00"))
    platform_net_credited = models.DecimalField(_("Platform Net Credited to Tenant"), max_digits=18, decimal_places=2, default=Decimal("0.00"))
    platform_refund_total = models.DecimalField(_("Platform Refund Total"), max_digits=18, decimal_places=2, default=Decimal("0.00"))

    gateway_transaction_count = models.PositiveIntegerField(_("Gateway Transaction Count"), default=0)
    gateway_gross_amount = models.DecimalField(_("Gateway Gross"), max_digits=18, decimal_places=2, default=Decimal("0.00"))
    gateway_fees = models.DecimalField(_("Gateway Fees"), max_digits=18, decimal_places=2, default=Decimal("0.00"))
    gateway_net_settled = models.DecimalField(_("Gateway Net Settled"), max_digits=18, decimal_places=2, default=Decimal("0.00"))
    gateway_refund_total = models.DecimalField(_("Gateway Refund Total"), max_digits=18, decimal_places=2, default=Decimal("0.00"))

    count_discrepancy = models.IntegerField(_("Count Discrepancy"), default=0)
    amount_discrepancy = models.DecimalField(_("Amount Discrepancy"), max_digits=18, decimal_places=2, default=Decimal("0.00"))
    discrepancy_detail = models.JSONField(_("Discrepancy Detail"), default=list, blank=True)
    discrepancy_resolved_at = models.DateTimeField(_("Discrepancy Resolved At"), null=True, blank=True)
    discrepancy_resolved_by = models.ForeignKey(
        "userauth.TenantUser",
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        related_name="resolved_reconciliations",
    )
    resolution_note = models.TextField(_("Resolution Note"), blank=True)

    gateway_settlement_id = models.CharField(_("Gateway Settlement ID"), max_length=500, blank=True)
    gateway_settlement_date = models.DateField(_("Gateway Settlement Date"), null=True, blank=True)
    gateway_raw_data = models.JSONField(_("Gateway Raw Settlement Data"), default=dict, blank=True)

    generated_at = models.DateTimeField(_("Generated At"), default=timezone.now)
    generated_by = models.CharField(_("Generated By"), max_length=50, default="system")
    error_detail = models.TextField(_("Error Detail"), blank=True)

    class Meta:
        verbose_name = _("Reconciliation Report")
        verbose_name_plural = _("Reconciliation Reports")
        unique_together = [("payment_profile", "report_date", "gateway_provider", "currency")]
        ordering = ["-report_date", "payment_profile"]
        indexes = [
            models.Index(fields=["report_date", "status"]),
            models.Index(fields=["payment_profile", "-report_date"]),
            models.Index(fields=["status"]),
        ]

    def __str__(self):
        return (
            f"Recon {self.report_date} - {self.gateway_provider} {self.currency} "
            f"[{self.status}] - Discrepancy: {self.amount_discrepancy}"
        )

    @property
    def is_clean(self) -> bool:
        return self.status == self.ReportStatus.MATCHED

    @property
    def has_discrepancy(self) -> bool:
        return self.amount_discrepancy != Decimal("0.00") or self.count_discrepancy != 0

    @property
    def system_total(self):
        return self.platform_net_credited

    @property
    def gateway_total(self):
        return self.gateway_net_settled

    @property
    def matched_count(self):
        return self.entries.filter(entry_status=ReconciliationEntry.EntryStatus.MATCHED).count()

    @property
    def total_count(self):
        return self.entries.count()


class ReconciliationEntry(AppendOnlyModel):
    class EntryStatus(models.TextChoices):
        MATCHED = "matched", _("Matched")
        PLATFORM_ONLY = "platform_only", _("Platform Only - Missing on Gateway")
        GATEWAY_ONLY = "gateway_only", _("Gateway Only - Missing on Platform")
        AMOUNT_MISMATCH = "amount_mismatch", _("Amount Mismatch")

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    report = models.ForeignKey(ReconciliationReport, on_delete=models.CASCADE, related_name="entries")

    platform_transaction_id = models.UUIDField(_("Platform Transaction ID"), null=True, blank=True, db_index=True)
    platform_reference = models.CharField(_("Platform Reference"), max_length=100, blank=True)
    platform_amount = models.DecimalField(_("Platform Amount"), max_digits=14, decimal_places=2, null=True, blank=True)
    platform_gateway_fee = models.DecimalField(_("Platform Gateway Fee"), max_digits=10, decimal_places=2, null=True, blank=True)
    platform_commission = models.DecimalField(_("Platform Commission"), max_digits=10, decimal_places=2, null=True, blank=True)
    platform_net = models.DecimalField(_("Platform Net"), max_digits=14, decimal_places=2, null=True, blank=True)
    platform_status = models.CharField(_("Platform Status"), max_length=15, blank=True)
    platform_paid_at = models.DateTimeField(_("Platform Paid At"), null=True, blank=True)

    gateway_transaction_id = models.CharField(_("Gateway Transaction ID"), max_length=500, blank=True)
    gateway_reference = models.CharField(_("Gateway Reference"), max_length=500, blank=True)
    gateway_amount = models.DecimalField(_("Gateway Amount"), max_digits=14, decimal_places=2, null=True, blank=True)
    gateway_fee = models.DecimalField(_("Gateway Fee"), max_digits=10, decimal_places=2, null=True, blank=True)
    gateway_net = models.DecimalField(_("Gateway Net"), max_digits=14, decimal_places=2, null=True, blank=True)
    gateway_status = models.CharField(_("Gateway Status"), max_length=50, blank=True)
    gateway_settled_at = models.DateTimeField(_("Gateway Settled At"), null=True, blank=True)

    entry_status = models.CharField(
        _("Entry Status"),
        max_length=20,
        choices=EntryStatus.choices,
        default=EntryStatus.MATCHED,
        db_index=True,
    )
    discrepancy_amount = models.DecimalField(_("Discrepancy Amount"), max_digits=14, decimal_places=2, default=Decimal("0.00"))
    discrepancy_note = models.TextField(_("Discrepancy Note"), blank=True)

    currency = models.CharField(_("Currency"), max_length=3)
    order_id = models.UUIDField(_("Order ID"), null=True, blank=True)
    order_number = models.CharField(_("Order Number"), max_length=100, blank=True)

    class Meta:
        verbose_name = _("Reconciliation Entry")
        verbose_name_plural = _("Reconciliation Entries")
        ordering = ["-created_at"]
        indexes = [
            models.Index(fields=["report", "entry_status"]),
            models.Index(fields=["platform_transaction_id"]),
        ]

    def __str__(self):
        return (
            f"ReconEntry [{self.entry_status}] - "
            f"Platform: {self.platform_amount}, Gateway: {self.gateway_amount} {self.currency}"
        )

    @property
    def transaction_reference(self):
        return self.platform_reference or self.gateway_reference or "—"

    @property
    def system_amount(self):
        return self.platform_amount

    @property
    def difference(self):
        return self.discrepancy_amount

    @property
    def match_status(self):
        mapping = {
            self.EntryStatus.MATCHED: "matched",
            self.EntryStatus.AMOUNT_MISMATCH: "mismatch",
            self.EntryStatus.PLATFORM_ONLY: "missing_in_gateway",
            self.EntryStatus.GATEWAY_ONLY: "missing_in_platform",
        }
        return mapping.get(self.entry_status, self.entry_status)

    @property
    def note(self):
        return self.discrepancy_note
