# Generated by Django 5.2 on 2026-07-28 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartdiscount',
            name='discount_type',
            field=models.CharField(choices=[('code', 'Coupon Code'), ('automatic', 'Automatic Discount'), ('bundle', 'Bundle Discount'), ('gift_card', 'Gift Card'), ('loyalty', 'Loyalty Points')], max_length=20, verbose_name='Discount Type'),
        ),
    ]
