from django.urls import path
from . import views
app_name = 'store_settings'

urlpatterns = [
    # The URL name 'manage_theme_settings' is used in the view redirect
    path('theme/', views.manage_theme_settings,
         name='manage_theme_settings'),
    # Theme Presets
    path('theme/presets/',
         views.theme_preset_list, name='theme_preset_list'),
    path('theme/presets/create/',
         views.theme_preset_create, name='theme_preset_create'),
    path('theme/presets/<int:pk>/edit/',
         views.theme_preset_edit, name='theme_preset_edit'),
    path('theme/presets/<int:pk>/delete/',
         views.theme_preset_delete, name='theme_preset_delete'),
    path('theme/presets/<int:pk>/details/',
         views.theme_preset_details, name='theme_preset_details'),
    #     path('theme/presets/<int:pk>/apply/',
    #          views.theme_preset_apply, name='theme_preset_apply'),
    #     path('theme/presets/<int:pk>/preview/',
    #          views.theme_preset_preview, name='theme_preset_preview'),
    #     path('theme/presets/<int:pk>/duplicate/',
    #          views.theme_preset_duplicate, name='theme_preset_duplicate'),

    #     # Store Settings
    path('store/', views.manage_store_settings,
         name='manage_store_settings'),
    #     path('store/<str:section>/',
    #          views.store_settings_section, name='store_settings_section'),

    #     # Social Media Links
    path('social/', views.manage_social_media_links,
         name='manage_social_media_links'),
    #     path('social/preview/',
    #          views.social_media_preview, name='social_media_preview'),
    #     path('social/test-instagram/',
    #          views.test_instagram_feed, name='test_instagram_feed'),

    #     # Search Settings
    #     path('search/', views.manage_search_settings,
    #          name='manage_search_settings'),
    #     path('search/test/',
    #          views.search_settings_test, name='search_settings_test'),

    #     # Product Page Settings
    path('product-page/',
         views.manage_product_page_settings, name='manage_product_page_settings'),
    #     path('product-page/preview/',
    #          views.product_page_preview, name='product_page_preview'),
    #     # Product Display Settings
    #     path('product-display/',
    #          views.manage_product_display_settings, name='manage_product_display_settings'),
    #     path('product-display/preview/',
    #          views.product_display_preview, name='product_display_preview'),
    #     # Popup Settings
    #     path('popups/', views.manage_popup_settings,
    #          name='manage_popup_settings'),
    #     path('popups/preview/',
    #          views.popup_preview, name='popup_preview'),
    #     path('popups/test-trigger/',
    #          views.test_popup_trigger, name='test_popup_trigger'),

    #     # Performance Settings
    #     path('performance/',
    #          views.manage_performance_settings, name='manage_performance_settings'),
    #     path('performance/test/',
    #          views.performance_test, name='performance_test'),
    #     path('performance/clear-cache/',
    #          views.clear_performance_cache, name='clear_performance_cache'),
    #     # Notification Settings
    #     path('notifications/',
    #          views.manage_notification_settings, name='manage_notification_settings'),
    #     path('notifications/test/<str:notification_type>/',
    #          views.test_notification, name='test_notification'),
    #     path('notifications/logs/',
    #          views.notification_logs, name='notification_logs'),

    #     # Navigation Menus
    #     path('dashboard/navigation/', views.navigation_menu_list,
    #          name='navigation_menu_list'),
    #     path('dashboard/navigation/create/',
    #          views.navigation_menu_create, name='navigation_menu_create'),
    #     path('dashboard/navigation/<int:pk>/edit/',
    #          views.navigation_menu_edit, name='navigation_menu_edit'),
    #     path('dashboard/navigation/<int:pk>/delete/',
    #          views.navigation_menu_delete, name='navigation_menu_delete'),
    #     path('dashboard/navigation/<int:pk>/preview/',
    #          views.navigation_menu_preview, name='navigation_menu_preview'),

    #     # Navigation Menu Items
    #     path('dashboard/navigation/<int:menu_pk>/items/create/',
    #          views.navigation_menu_item_create, name='navigation_menu_item_create'),
    #     path('dashboard/navigation/items/<int:item_pk>/edit/',
    #          views.navigation_menu_item_edit, name='navigation_menu_item_edit'),
    #     path('dashboard/navigation/items/<int:item_pk>/delete/',
    #          views.navigation_menu_item_delete, name='navigation_menu_item_delete'),
    #     path('dashboard/navigation/items/reorder/',
    #          views.navigation_menu_item_reorder, name='navigation_menu_item_reorder'),
    #     Mobile App Settings
    #     path('mobile-app/',
    #          views.manage_mobile_app_settings, name='manage_mobile_app_settings'),
    #     path('mobile-app/preview/',
    #          views.mobile_app_preview, name='mobile_app_preview'),
    #     path('mobile-app/test-push/',
    #          views.test_push_notification, name='test_push_notification'),
    #     # Homepage Layout
    #     path('homepage/',
    #          views.manage_homepage_layout, name='manage_homepage_layout'),
    #     path('homepage/preview/',
    #          views.homepage_preview, name='homepage_preview'),
    #     path('homepage/reset/',
    #          views.reset_homepage_layout, name='reset_homepage_layout'),
    #     # Header Settings
    #     path('header/', views.manage_header_settings,
    #          name='manage_header_settings'),
    #     path('header/preview/',
    #          views.header_preview, name='header_preview'),
    #     path('header/reset/',
    #          views.reset_header_settings, name='reset_header_settings'),
    #     # Footer Settings
    #     path('footer/', views.manage_footer_settings,
    #          name='manage_footer_settings'),
    #     path('footer/preview/',
    #          views.footer_preview, name='footer_preview'),
    #     path('footer/reset/',
    #          views.reset_footer_settings, name='reset_footer_settings'),
    #     # Email Template Settings
    #     path('email-templates/',
    #          views.manage_email_template_settings, name='manage_email_template_settings'),
    #     path('email-templates/preview/<str:email_type>/',
    #          views.email_template_preview, name='email_template_preview'),
    #     path('email-templates/test/<str:email_type>/',
    #          views.send_test_email, name='send_test_email'),
    #     path('email-templates/reset/',
    #          # Email Template Settings
    #          views.reset_email_template_settings, name='reset_email_template_settings'),
    #     path('email-templates/',
    #          views.manage_email_template_settings, name='manage_email_template_settings'),
    #     path('email-templates/preview/<str:email_type>/',
    #          views.email_template_preview, name='email_template_preview'),
    #     path('email-templates/test/<str:email_type>/',
    #          views.send_test_email, name='send_test_email'),
    #     path('email-templates/reset/',
    #          views.reset_email_template_settings, name='reset_email_template_settings'),
    #     # Custom CSS
    #     path('dashboard/css/', views.custom_css_list, name='custom_css_list'),
    #     path('dashboard/css/create/', views.custom_css_create,
    #          name='custom_css_create'),
    #     path('dashboard/css/<int:pk>/edit/',
    #          views.custom_css_edit, name='custom_css_edit'),
    #     path('dashboard/css/<int:pk>/delete/',
    #          views.custom_css_delete, name='custom_css_delete'),
    #     path('dashboard/css/<int:pk>/duplicate/',
    #          views.custom_css_duplicate, name='custom_css_duplicate'),
    #     path('dashboard/css/<int:pk>/preview/',
    #          views.custom_css_preview, name='custom_css_preview'),
    #     path('dashboard/css/bulk-action/', views.custom_css_bulk_action,
    #          name='custom_css_bulk_action'),
    #     path('dashboard/css/stats/', views.custom_css_stats, name='custom_css_stats'),
    #     path('dashboard/css/validate/', views.validate_css_syntax,
    #          name='validate_css_syntax'),
    #     # Checkout Settings
    #     path('checkout/', views.manage_checkout_settings,
    #          name='manage_checkout_settings'),
    #     path('checkout/preview/',
    #          views.checkout_preview, name='checkout_preview'),
    #     path('checkout/reset/',
    #          views.reset_checkout_settings, name='reset_checkout_settings'),
    #     # Cart Settings
    #     path('cart/', views.manage_cart_settings,
    #          name='manage_cart_settings'),
    #     path('cart/preview/',
    #          views.cart_preview, name='cart_preview'),
    #     path('cart/reset/',
    #          views.reset_cart_settings, name='reset_cart_settings'),

    #     # Blog Settings
    #     path('blog/', views.manage_blog_settings,
    #          name='manage_blog_settings'),
    #     path('blog/preview/',
    #          views.blog_preview, name='blog_preview'),
    #     path('blog/reset/',
    #          views.reset_blog_settings, name='reset_blog_settings'),
    #     # Banner Slides
    #     path('dashboard/banners/', views.banner_slide_list, name='banner_slide_list'),
    #     path('dashboard/banners/create/',
    #          views.banner_slide_create, name='banner_slide_create'),
    #     path('dashboard/banners/<int:pk>/edit/',
    #          views.banner_slide_edit, name='banner_slide_edit'),
    #     path('dashboard/banners/<int:pk>/delete/',
    #          views.banner_slide_delete, name='banner_slide_delete'),
    #     path('dashboard/banners/<int:pk>/duplicate/',
    #          views.banner_slide_duplicate, name='banner_slide_duplicate'),
    #     path('dashboard/banners/<int:pk>/preview/',
    #          views.banner_slide_preview, name='banner_slide_preview'),
    #     path('dashboard/banners/bulk-action/',
    #          views.banner_slide_bulk_action, name='banner_slide_bulk_action'),
    #     path('dashboard/banners/reorder/',
    #          views.banner_slide_reorder, name='banner_slide_reorder'),
    #     path('dashboard/banners/stats/',
    #          views.banner_slide_stats, name='banner_slide_stats'),

]
