# Generated by Django 5.2 on 2026-04-14 15:38

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ThemeCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Theme Category',
                'verbose_name_plural': 'Theme Categories',
                'db_table': 'shared_theme_categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('version', models.CharField(default='1.0.0', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('is_free', models.BooleanField(default=True)),
                ('zip_file', models.FileField(upload_to='themes/uploads/')),
                ('thumbnail', models.ImageField(blank=True, upload_to='themes/thumbnails/')),
                ('folder_path', models.CharField(max_length=500)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('suspended', 'Suspended')], db_index=True, default='draft', max_length=20)),
                ('is_published', models.BooleanField(db_index=True, default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('downloads', models.PositiveIntegerField(default=0)),
                ('rating', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=3)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_themes', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='themes', to='theme_marketplace.themecategory')),
            ],
            options={
                'verbose_name': 'Theme',
                'verbose_name_plural': 'Themes',
                'db_table': 'shared_themes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ThemeBasePage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('page_name', models.CharField(db_index=True, max_length=100)),
                ('file_path', models.CharField(max_length=500)),
                ('css_path', models.CharField(blank=True, max_length=500)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_required', models.BooleanField(default=True)),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='base_pages', to='theme_marketplace.theme')),
            ],
            options={
                'verbose_name': 'Theme Base Page',
                'verbose_name_plural': 'Theme Base Pages',
                'db_table': 'shared_theme_pages',
                'unique_together': {('theme', 'page_name')},
            },
        ),
    ]
