# Generated by Django 5.2 on 2026-04-27 11:16

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('theme_marketplace', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='theme',
            options={'ordering': ['-is_featured', 'name'], 'verbose_name': 'Theme', 'verbose_name_plural': 'Themes'},
        ),
        migrations.AlterModelOptions(
            name='themebasepage',
            options={'ordering': ['page_name'], 'verbose_name': 'Theme Base Page', 'verbose_name_plural': 'Theme Base Pages'},
        ),
        migrations.AddField(
            model_name='theme',
            name='currency',
            field=models.CharField(default='NGN', max_length=3),
        ),
        migrations.AddField(
            model_name='theme',
            name='feature_bullets',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='theme',
            name='manifest',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='theme',
            name='preview_image_path',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='theme',
            name='source',
            field=models.CharField(choices=[('builtin', 'Built-in'), ('uploaded', 'Uploaded / Legacy')], db_index=True, default='builtin', max_length=20),
        ),
        migrations.AddField(
            model_name='theme',
            name='thumbnail_path',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='theme',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_themes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='theme',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='theme',
            name='folder_path',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='theme',
            name='zip_file',
            field=models.FileField(blank=True, upload_to='themes/uploads/'),
        ),
        migrations.AlterField(
            model_name='themebasepage',
            name='page_name',
            field=models.CharField(db_index=True, max_length=150),
        ),
        migrations.CreateModel(
            name='TenantActiveTheme',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('schema_name', models.CharField(db_index=True, max_length=63, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shop', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='active_theme_record', to='core.shop')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='active_tenants', to='theme_marketplace.theme')),
            ],
            options={
                'verbose_name': 'Tenant Active Theme',
                'verbose_name_plural': 'Tenant Active Themes',
                'db_table': 'shared_tenant_active_theme',
                'ordering': ['schema_name'],
            },
        ),
        migrations.CreateModel(
            name='TenantThemeAccess',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('schema_name', models.CharField(db_index=True, max_length=63)),
                ('access_type', models.CharField(choices=[('free', 'Free'), ('purchased', 'Purchased')], default='free', max_length=12)),
                ('purchase_date', models.DateTimeField(blank=True, null=True)),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('payment_reference', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='theme_access_records', to='core.shop')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_access_records', to='theme_marketplace.theme')),
            ],
            options={
                'verbose_name': 'Tenant Theme Access',
                'verbose_name_plural': 'Tenant Theme Access',
                'db_table': 'shared_tenant_theme_access',
                'ordering': ['schema_name', 'theme__name'],
                'indexes': [models.Index(fields=['schema_name', 'is_active'], name='shared_tena_schema__01a26c_idx'), models.Index(fields=['theme', 'is_active'], name='shared_tena_theme_i_294297_idx')],
                'unique_together': {('schema_name', 'theme')},
            },
        ),
        migrations.CreateModel(
            name='ThemeSwitchLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('schema_name', models.CharField(db_index=True, max_length=63)),
                ('switched_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('switched_by_user_id', models.CharField(blank=True, max_length=100)),
                ('switched_by_email', models.EmailField(blank=True, max_length=254)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('from_theme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='switches_from', to='theme_marketplace.theme')),
                ('shop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='theme_switch_logs', to='core.shop')),
                ('to_theme', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='switches_to', to='theme_marketplace.theme')),
            ],
            options={
                'verbose_name': 'Theme Switch Log',
                'verbose_name_plural': 'Theme Switch Logs',
                'db_table': 'shared_theme_switch_log',
                'ordering': ['-switched_at'],
                'indexes': [models.Index(fields=['schema_name', '-switched_at'], name='shared_them_schema__fe01fc_idx'), models.Index(fields=['to_theme', '-switched_at'], name='shared_them_to_them_aab6a3_idx')],
            },
        ),
    ]
