# Generated by Django 5.2 on 2026-04-27 13:43

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('theme_marketplace', '0002_alter_theme_options_alter_themebasepage_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantthemeaccess',
            name='acquired_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='tenantthemeaccess',
            name='revoked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='changelog_path',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='theme',
            name='demo_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='is_internal',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='theme',
            name='preview_gallery',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='theme',
            name='schema_path',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.CreateModel(
            name='TenantThemeContent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('schema_name', models.CharField(db_index=True, max_length=63)),
                ('universal_content', models.JSONField(blank=True, default=dict)),
                ('theme_content', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='theme_content_records', to='core.shop')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_content_records', to='theme_marketplace.theme')),
            ],
            options={
                'db_table': 'shared_tenant_theme_content',
                'ordering': ['schema_name', 'theme__name'],
                'unique_together': {('schema_name', 'theme')},
            },
        ),
        migrations.CreateModel(
            name='TenantThemeAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('asset_key', models.CharField(db_index=True, max_length=120)),
                ('asset_label', models.CharField(blank=True, max_length=160)),
                ('asset_type', models.CharField(default='image', max_length=40)),
                ('file', models.FileField(blank=True, upload_to='themes/assets/%Y/%m/')),
                ('remote_url', models.URLField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='theme_marketplace.tenantthemecontent')),
            ],
            options={
                'db_table': 'shared_tenant_theme_assets',
                'ordering': ['asset_key', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ThemeOffer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('offer_type', models.CharField(choices=[('free', 'Free'), ('one_time', 'One Time'), ('subscription', 'Subscription'), ('limited_release', 'Limited Release'), ('seasonal', 'Seasonal'), ('discount', 'Discount')], db_index=True, default='free', max_length=20)),
                ('billing_interval', models.CharField(choices=[('none', 'None'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], default='none', max_length=20)),
                ('currency', models.CharField(default='NGN', max_length=3)),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('compare_at_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='theme_marketplace.theme')),
            ],
            options={
                'db_table': 'shared_theme_offers',
                'ordering': ['theme__name', '-is_default', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ThemeReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reviewer_name', models.CharField(max_length=120)),
                ('reviewer_email', models.EmailField(blank=True, max_length=254)),
                ('rating', models.PositiveSmallIntegerField(default=5)),
                ('title', models.CharField(blank=True, max_length=160)),
                ('body', models.TextField(blank=True)),
                ('is_published', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='theme_marketplace.theme')),
            ],
            options={
                'db_table': 'shared_theme_reviews',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TenantInstalledTheme',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('schema_name', models.CharField(db_index=True, max_length=63)),
                ('installed_version', models.CharField(blank=True, max_length=20)),
                ('schema_version', models.CharField(blank=True, max_length=20)),
                ('install_status', models.CharField(choices=[('installed', 'Installed'), ('disabled', 'Disabled'), ('removed', 'Removed')], db_index=True, default='installed', max_length=20)),
                ('default_config', models.JSONField(blank=True, default=dict)),
                ('installed_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('removed_at', models.DateTimeField(blank=True, null=True)),
                ('shop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='installed_themes', to='core.shop')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installed_tenants', to='theme_marketplace.theme')),
            ],
            options={
                'db_table': 'shared_tenant_installed_theme',
                'ordering': ['schema_name', 'theme__name'],
                'unique_together': {('schema_name', 'theme')},
            },
        ),
        migrations.CreateModel(
            name='ThemeRelease',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.CharField(db_index=True, max_length=20)),
                ('title', models.CharField(blank=True, max_length=160)),
                ('changelog', models.TextField(blank=True)),
                ('released_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='releases', to='theme_marketplace.theme')),
            ],
            options={
                'db_table': 'shared_theme_releases',
                'ordering': ['-released_at'],
                'unique_together': {('theme', 'version')},
            },
        ),
    ]
