# Generated by Django 5.2 on 2026-03-26 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('notification', '0001_initial'),
        ('userauth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerdevice',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='userauth.customer', verbose_name='Customer'),
        ),
        migrations.AddField(
            model_name='inappnotification',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Null = system-generated.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_inapp_notifications', to='userauth.tenantuser', verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='inappnotificationread',
            name='notification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_states', to='notification.inappnotification', verbose_name='Notification'),
        ),
        migrations.AddField(
            model_name='inappnotificationread',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_read_states', to='userauth.tenantuser', verbose_name='User'),
        ),
        migrations.AddField(
            model_name='notificationblacklist',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_blacklist_entries', to='userauth.tenantuser'),
        ),
        migrations.AddField(
            model_name='notificationchannel',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_notification_channels', to='userauth.tenantuser'),
        ),
        migrations.AddField(
            model_name='emailchannelconfig',
            name='channel',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='email_config', to='notification.notificationchannel', verbose_name='Channel'),
        ),
        migrations.AddField(
            model_name='notificationdailysummary',
            name='channel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_summaries', to='notification.notificationchannel', verbose_name='Channel'),
        ),
        migrations.AddField(
            model_name='notificationjob',
            name='channel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='notification.notificationchannel', verbose_name='Channel'),
        ),
        migrations.AddField(
            model_name='notificationjob',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_jobs', to='userauth.customer', verbose_name='Customer'),
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='channel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='notification.notificationchannel', verbose_name='Channel'),
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_logs', to='userauth.customer', verbose_name='Customer'),
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='notification.notificationjob', verbose_name='Notification Job'),
        ),
        migrations.AddField(
            model_name='notificationevent',
            name='notification_log',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='notification.notificationlog', verbose_name='Notification Log'),
        ),
        migrations.AddField(
            model_name='bouncerecord',
            name='notification_log',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bounces', to='notification.notificationlog', verbose_name='Notification Log'),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_preferences', to='notification.notificationcategory', verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to='userauth.customer', verbose_name='Customer'),
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='ab_test_variant_b',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ab_test_variants_for', to='notification.notificationtemplate', verbose_name='A/B Test Variant B Template'),
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='templates', to='notification.notificationcategory', verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='channel',
            field=models.ForeignKey(blank=True, help_text='The channel this template sends through. Null = route by event at send time.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='templates', to='notification.notificationchannel', verbose_name='Notification Channel'),
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_notification_templates', to='userauth.tenantuser'),
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_notification_templates', to='userauth.tenantuser'),
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='notification.notificationtemplate', verbose_name='Template'),
        ),
        migrations.AddField(
            model_name='notificationjob',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='notification.notificationtemplate', verbose_name='Template'),
        ),
        migrations.AddField(
            model_name='notificationdailysummary',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_summaries', to='notification.notificationtemplate', verbose_name='Template'),
        ),
        migrations.AddField(
            model_name='notificationtemplateversion',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_template_versions', to='userauth.tenantuser'),
        ),
        migrations.AddField(
            model_name='notificationtemplateversion',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='notification.notificationtemplate', verbose_name='Template'),
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='active_version',
            field=models.ForeignKey(blank=True, help_text='The currently live version of this template.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_for_templates', to='notification.notificationtemplateversion', verbose_name='Active Version'),
        ),
        migrations.AddField(
            model_name='notificationjob',
            name='template_version',
            field=models.ForeignKey(blank=True, help_text="Pinned version at job creation time. Ensures template changes don't affect queued jobs.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='notification.notificationtemplateversion', verbose_name='Template Version'),
        ),
        migrations.AddField(
            model_name='pushchannelconfig',
            name='channel',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='push_config', to='notification.notificationchannel', verbose_name='Channel'),
        ),
        migrations.AddField(
            model_name='slackchannelconfig',
            name='channel',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='slack_config', to='notification.notificationchannel', verbose_name='Channel'),
        ),
        migrations.AddField(
            model_name='smschannelconfig',
            name='channel',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sms_config', to='notification.notificationchannel', verbose_name='Channel'),
        ),
        migrations.AddField(
            model_name='spamcomplaint',
            name='notification_log',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spam_complaints', to='notification.notificationlog', verbose_name='Notification Log'),
        ),
        migrations.AddField(
            model_name='templatevariable',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variables', to='notification.notificationtemplate', verbose_name='Template'),
        ),
        migrations.AddField(
            model_name='unsubscribetoken',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Null = global unsubscribe (all categories).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unsubscribe_tokens', to='notification.notificationcategory', verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='unsubscribetoken',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unsubscribe_tokens', to='userauth.customer', verbose_name='Customer'),
        ),
        migrations.AddField(
            model_name='webhookendpoint',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_webhook_endpoints', to='userauth.tenantuser'),
        ),
        migrations.AddField(
            model_name='webhookdeliveryattempt',
            name='endpoint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_attempts', to='notification.webhookendpoint', verbose_name='Endpoint'),
        ),
        migrations.AddField(
            model_name='webhookeventsubscription',
            name='endpoint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='notification.webhookendpoint', verbose_name='Endpoint'),
        ),
        migrations.AddField(
            model_name='webhookdeliveryattempt',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_attempts', to='notification.webhookeventsubscription', verbose_name='Subscription'),
        ),
        migrations.AddField(
            model_name='webhooksigningsecret',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_signing_secrets', to='userauth.tenantuser'),
        ),
        migrations.AddField(
            model_name='webhooksigningsecret',
            name='endpoint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signing_secrets', to='notification.webhookendpoint', verbose_name='Endpoint'),
        ),
        migrations.AddIndex(
            model_name='customerdevice',
            index=models.Index(fields=['customer', 'platform', 'status'], name='notificatio_custome_4aa79f_idx'),
        ),
        migrations.AddIndex(
            model_name='customerdevice',
            index=models.Index(fields=['push_token_hash'], name='notificatio_push_to_236963_idx'),
        ),
        migrations.AddIndex(
            model_name='customerdevice',
            index=models.Index(fields=['device_fingerprint'], name='notificatio_device__30bbfc_idx'),
        ),
        migrations.AddIndex(
            model_name='customerdevice',
            index=models.Index(fields=['status'], name='notificatio_status_9decda_idx'),
        ),
        migrations.AddIndex(
            model_name='inappnotification',
            index=models.Index(fields=['audience', 'is_active'], name='notificatio_audienc_8936d1_idx'),
        ),
        migrations.AddIndex(
            model_name='inappnotification',
            index=models.Index(fields=['is_active', 'expires_at'], name='notificatio_is_acti_343940_idx'),
        ),
        migrations.AddIndex(
            model_name='inappnotification',
            index=models.Index(fields=['source_event', '-created_at'], name='notificatio_source__c355c5_idx'),
        ),
        migrations.AddIndex(
            model_name='inappnotification',
            index=models.Index(fields=['source_object_type', 'source_object_id'], name='notificatio_source__234375_idx'),
        ),
        migrations.AddIndex(
            model_name='inappnotification',
            index=models.Index(fields=['notification_type', 'audience'], name='notificatio_notific_d5e49a_idx'),
        ),
        migrations.AddIndex(
            model_name='inappnotificationread',
            index=models.Index(fields=['user', 'notification'], name='notificatio_user_id_40d0d2_idx'),
        ),
        migrations.AddIndex(
            model_name='inappnotificationread',
            index=models.Index(fields=['user', 'dismissed_at'], name='notificatio_user_id_16e625_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='inappnotificationread',
            unique_together={('notification', 'user')},
        ),
        migrations.AddIndex(
            model_name='notificationblacklist',
            index=models.Index(fields=['entry_type', 'value_hash'], name='notificatio_entry_t_bf91bb_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationblacklist',
            index=models.Index(fields=['reason'], name='notificatio_reason_c86671_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationblacklist',
            index=models.Index(fields=['expires_at'], name='notificatio_expires_d09442_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='notificationblacklist',
            unique_together={('entry_type', 'value_hash')},
        ),
        migrations.AddIndex(
            model_name='notificationchannel',
            index=models.Index(fields=['channel_type', 'status'], name='notificatio_channel_d68d79_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationchannel',
            index=models.Index(fields=['channel_type', 'is_default'], name='notificatio_channel_80e22d_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationchannel',
            index=models.Index(fields=['status'], name='notificatio_status_1d943d_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationevent',
            index=models.Index(fields=['notification_log', 'event_type'], name='notificatio_notific_813dd8_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationevent',
            index=models.Index(fields=['event_type', '-created_at'], name='notificatio_event_t_25f544_idx'),
        ),
        migrations.AddIndex(
            model_name='bouncerecord',
            index=models.Index(fields=['email_address', 'bounce_type'], name='notificatio_email_a_373ff4_idx'),
        ),
        migrations.AddIndex(
            model_name='bouncerecord',
            index=models.Index(fields=['bounce_type', '-created_at'], name='notificatio_bounce__6e98c4_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationpreference',
            index=models.Index(fields=['customer', 'is_subscribed'], name='notificatio_custome_708725_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationpreference',
            index=models.Index(fields=['category', 'channel_type', 'is_subscribed'], name='notificatio_categor_91e73c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='notificationpreference',
            unique_together={('customer', 'category', 'channel_type')},
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['status', '-created_at'], name='notificatio_status_df4bd4_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['channel_type', '-created_at'], name='notificatio_channel_8b0656_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['event_slug', '-created_at'], name='notificatio_event_s_73de92_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['customer', '-created_at'], name='notificatio_custome_2e5c9d_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['recipient_address', '-created_at'], name='notificatio_recipie_a0872f_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['provider_message_id'], name='notificatio_provide_d40d9b_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['event_object_type', 'event_object_id'], name='notificatio_event_o_438e2f_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['template', 'status'], name='notificatio_templat_4ac1da_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationdailysummary',
            index=models.Index(fields=['date', 'channel_type'], name='notificatio_date_150f1c_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationdailysummary',
            index=models.Index(fields=['date', 'template'], name='notificatio_date_414540_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationdailysummary',
            index=models.Index(fields=['event_slug', 'date'], name='notificatio_event_s_6c5d18_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationdailysummary',
            index=models.Index(fields=['-date', 'open_rate'], name='notificatio_date_125a3d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='notificationdailysummary',
            unique_together={('date', 'channel_type', 'template', 'event_slug')},
        ),
        migrations.AddIndex(
            model_name='notificationtemplateversion',
            index=models.Index(fields=['template', '-version_number'], name='notificatio_templat_66a686_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='notificationtemplateversion',
            unique_together={('template', 'version_number')},
        ),
        migrations.AddIndex(
            model_name='notificationtemplate',
            index=models.Index(fields=['event_slug', 'channel_type', 'is_enabled'], name='notificatio_event_s_585b71_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationtemplate',
            index=models.Index(fields=['status', 'is_enabled'], name='notificatio_status_951d40_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationtemplate',
            index=models.Index(fields=['category', 'status'], name='notificatio_categor_76febf_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='notificationtemplate',
            unique_together={('event_slug', 'channel_type', 'locale')},
        ),
        migrations.AddIndex(
            model_name='notificationjob',
            index=models.Index(fields=['status', 'priority', 'send_at'], name='notificatio_status_3f5f75_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationjob',
            index=models.Index(fields=['status', 'next_attempt_at'], name='notificatio_status_31476f_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationjob',
            index=models.Index(fields=['event_slug', 'status'], name='notificatio_event_s_ddae4b_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationjob',
            index=models.Index(fields=['dedup_key'], name='notificatio_dedup_k_538fc3_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationjob',
            index=models.Index(fields=['event_object_type', 'event_object_id'], name='notificatio_event_o_19f16f_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationjob',
            index=models.Index(fields=['customer', 'status'], name='notificatio_custome_0d226b_idx'),
        ),
        migrations.AddIndex(
            model_name='spamcomplaint',
            index=models.Index(fields=['email_address'], name='notificatio_email_a_a85d1f_idx'),
        ),
        migrations.AddIndex(
            model_name='spamcomplaint',
            index=models.Index(fields=['provider', '-created_at'], name='notificatio_provide_22c261_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='templatevariable',
            unique_together={('template', 'key')},
        ),
        migrations.AddIndex(
            model_name='unsubscribetoken',
            index=models.Index(fields=['token'], name='notificatio_token_ba5da0_idx'),
        ),
        migrations.AddIndex(
            model_name='unsubscribetoken',
            index=models.Index(fields=['customer', 'channel_type'], name='notificatio_custome_b5ae41_idx'),
        ),
        migrations.AddIndex(
            model_name='webhookendpoint',
            index=models.Index(fields=['status'], name='notificatio_status_a65544_idx'),
        ),
        migrations.AddIndex(
            model_name='webhookeventsubscription',
            index=models.Index(fields=['event_slug', 'is_active'], name='notificatio_event_s_7f2327_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='webhookeventsubscription',
            unique_together={('endpoint', 'event_slug')},
        ),
        migrations.AddIndex(
            model_name='webhookdeliveryattempt',
            index=models.Index(fields=['endpoint', '-created_at'], name='notificatio_endpoin_16f380_idx'),
        ),
        migrations.AddIndex(
            model_name='webhookdeliveryattempt',
            index=models.Index(fields=['event_id', 'attempt_number'], name='notificatio_event_i_f5ae6f_idx'),
        ),
        migrations.AddIndex(
            model_name='webhookdeliveryattempt',
            index=models.Index(fields=['is_successful', '-created_at'], name='notificatio_is_succ_fa03c9_idx'),
        ),
        migrations.AddIndex(
            model_name='webhookdeliveryattempt',
            index=models.Index(fields=['next_retry_at'], name='notificatio_next_re_ed2dcf_idx'),
        ),
        migrations.AddIndex(
            model_name='webhookdeliveryattempt',
            index=models.Index(fields=['event_slug', '-created_at'], name='notificatio_event_s_8e095a_idx'),
        ),
        migrations.AddIndex(
            model_name='webhooksigningsecret',
            index=models.Index(fields=['endpoint', 'status'], name='notificatio_endpoin_d026f4_idx'),
        ),
    ]
