from __future__ import annotations

from system.feature_marketplace.models import BillingCycle, DiscountType


STARTER_FEATURES = [
    {
        "category": "Operations",
        "slug": "operations",
        "feature": {
            "name": "Max Products",
            "code": "max_products",
            "feature_type": "limit",
            "unit_label": "products",
            "default_limit_value": 50,
            "short_description": "Increase catalog capacity.",
            "description": "Free stores can publish up to 50 products. Buy more capacity as the catalog grows.",
            "icon": "inventory_2",
            "display_order": 40,
        },
        "prices": [
            {"currency": "NGN", "billing_cycle": BillingCycle.MONTHLY, "amount": "4000.00", "limit_increment": 100},
            {"currency": "NGN", "billing_cycle": BillingCycle.ANNUAL, "amount": "40000.00", "limit_increment": 100},
        ],
    },
    {
        "category": "Storefront",
        "slug": "storefront",
        "feature": {
            "name": "Reviews",
            "code": "reviews",
            "feature_type": "boolean",
            "store_setting_key": "enable_reviews",
            "storefront_flag": "enable_reviews",
            "short_description": "Enable storefront product reviews.",
            "icon": "rate_review",
            "display_order": 60,
        },
        "prices": [
            {"currency": "NGN", "billing_cycle": BillingCycle.MONTHLY, "amount": "3000.00"},
            {"currency": "NGN", "billing_cycle": BillingCycle.ANNUAL, "amount": "30000.00"},
        ],
    },
]


REALISTIC_PLUS_FEATURES = [
    {
        "category": "Analytics",
        "slug": "analytics",
        "feature": {
            "name": "Advanced Analytics",
            "code": "advanced_analytics",
            "feature_type": "boolean",
            "short_description": "Unlock payment and growth dashboards with deeper insight.",
            "description": "Adds premium analytics surfaces and richer reporting views across tenant payments and marketplace activity.",
            "icon": "analytics",
            "badge_label": "Popular",
            "sidebar_key": "payments_analytics",
            "is_featured": True,
            "display_order": 10,
        },
        "prices": [
            {"currency": "NGN", "billing_cycle": BillingCycle.MONTHLY, "amount": "7500.00"},
            {"currency": "NGN", "billing_cycle": BillingCycle.ANNUAL, "amount": "75000.00"},
        ],
    },
    {
        "category": "Analytics",
        "slug": "analytics",
        "feature": {
            "name": "Advanced Reports",
            "code": "advanced_reports",
            "feature_type": "boolean",
            "short_description": "Unlock deeper reporting exports and historical views.",
            "description": "Adds richer report slices for operators who need more than the default analytics surfaces.",
            "icon": "query_stats",
            "display_order": 20,
        },
        "prices": [
            {"currency": "NGN", "billing_cycle": BillingCycle.MONTHLY, "amount": "5000.00"},
            {"currency": "NGN", "billing_cycle": BillingCycle.ANNUAL, "amount": "50000.00"},
        ],
    },
    {
        "category": "Operations",
        "slug": "operations",
        "feature": {
            "name": "Staff Management",
            "code": "staff_management",
            "feature_type": "limit",
            "short_description": "Increase the number of active staff seats.",
            "description": "Expands the staff seat quota used by the tenant dashboard staff management area.",
            "unit_label": "staff seats",
            "default_limit_value": 0,
            "icon": "badge",
            "display_order": 30,
        },
        "prices": [
            {"currency": "NGN", "billing_cycle": BillingCycle.MONTHLY, "amount": "2500.00", "limit_increment": 5},
            {"currency": "NGN", "billing_cycle": BillingCycle.ANNUAL, "amount": "25000.00", "limit_increment": 5},
        ],
    },
    {
        "category": "Operations",
        "slug": "operations",
        "feature": {
            "name": "Max Products",
            "code": "max_products",
            "feature_type": "limit",
            "short_description": "Increase how many products the store can publish.",
            "description": "Free stores start with 50 products. Buy extra capacity as the catalog grows.",
            "unit_label": "products",
            "default_limit_value": 50,
            "icon": "inventory_2",
            "badge_label": "Free 50",
            "display_order": 40,
        },
        "prices": [
            {"currency": "NGN", "billing_cycle": BillingCycle.MONTHLY, "amount": "4000.00", "limit_increment": 100},
            {"currency": "NGN", "billing_cycle": BillingCycle.ANNUAL, "amount": "40000.00", "limit_increment": 100},
        ],
    },
    {
        "category": "Operations",
        "slug": "operations",
        "feature": {
            "name": "POS Locations",
            "code": "max_pos_locations",
            "feature_type": "limit",
            "short_description": "Unlock monthly POS location capacity.",
            "description": "Point of Sale is not included for free stores. Each monthly purchase adds one active POS location slot.",
            "unit_label": "POS locations",
            "default_limit_value": 0,
            "icon": "point_of_sale",
            "badge_label": "Monthly",
            "sidebar_key": "pos",
            "display_order": 45,
            "metadata": {
                "module_unlock": True,
                "module_key": "pos",
            },
        },
        "prices": [
            {"currency": "NGN", "billing_cycle": BillingCycle.MONTHLY, "amount": "12000.00", "limit_increment": 1},
        ],
    },
    {
        "category": "Operations",
        "slug": "operations",
        "feature": {
            "name": "Custom Domain Slots",
            "code": "max_custom_domains",
            "feature_type": "limit",
            "short_description": "Unlock annual custom domain capacity.",
            "description": "Custom domains are not part of the free baseline. Each annual purchase adds one domain slot.",
            "unit_label": "custom domains",
            "default_limit_value": 0,
            "icon": "language",
            "badge_label": "Annual",
            "sidebar_key": "domains",
            "display_order": 50,
            "metadata": {
                "module_unlock": True,
                "module_key": "domains",
            },
        },
        "prices": [
            {"currency": "NGN", "billing_cycle": BillingCycle.ANNUAL, "amount": "15000.00", "limit_increment": 1},
        ],
    },
    {
        "category": "AI",
        "slug": "ai",
        "feature": {
            "name": "AI Credits",
            "code": "ai_credits",
            "feature_type": "usage",
            "short_description": "Usage-based credits for AI features.",
            "description": "Supplies consumption-based credits that can be spent by future AI-assisted tenant workflows.",
            "unit_label": "credits",
            "default_usage_value": 0,
            "icon": "auto_awesome",
            "badge_label": "Usage",
            "display_order": 60,
        },
        "prices": [
            {"currency": "NGN", "billing_cycle": BillingCycle.ONE_TIME, "amount": "5000.00", "credits_included": 5000},
            {"currency": "NGN", "billing_cycle": BillingCycle.MONTHLY, "amount": "9000.00", "credits_included": 12000},
            {"currency": "NGN", "billing_cycle": BillingCycle.ANNUAL, "amount": "90000.00", "credits_included": 144000},
        ],
    },
    {
        "category": "Storefront",
        "slug": "storefront",
        "feature": {
            "name": "Reviews",
            "code": "reviews",
            "feature_type": "boolean",
            "short_description": "Enable product reviews in the storefront.",
            "description": "Turns on the reviews storefront feature and its related tenant settings.",
            "store_setting_key": "enable_reviews",
            "storefront_flag": "enable_reviews",
            "icon": "rate_review",
            "display_order": 70,
        },
        "prices": [
            {"currency": "NGN", "billing_cycle": BillingCycle.MONTHLY, "amount": "3000.00"},
            {"currency": "NGN", "billing_cycle": BillingCycle.ANNUAL, "amount": "30000.00"},
        ],
    },
    {
        "category": "Storefront",
        "slug": "storefront",
        "feature": {
            "name": "Wishlist",
            "code": "wishlist",
            "feature_type": "boolean",
            "short_description": "Enable customer wishlists.",
            "description": "Turns on wishlist flows in the storefront and settings layer.",
            "store_setting_key": "enable_wishlist",
            "storefront_flag": "enable_wishlist",
            "icon": "favorite",
            "display_order": 80,
        },
        "prices": [
            {"currency": "NGN", "billing_cycle": BillingCycle.MONTHLY, "amount": "3000.00"},
            {"currency": "NGN", "billing_cycle": BillingCycle.ANNUAL, "amount": "30000.00"},
        ],
    },
    {
        "category": "Storefront",
        "slug": "storefront",
        "feature": {
            "name": "Compare",
            "code": "compare",
            "feature_type": "boolean",
            "short_description": "Enable product compare flows.",
            "description": "Turns on the compare experience in the storefront.",
            "store_setting_key": "enable_compare",
            "storefront_flag": "enable_compare",
            "icon": "compare_arrows",
            "display_order": 90,
        },
        "prices": [
            {"currency": "NGN", "billing_cycle": BillingCycle.MONTHLY, "amount": "2500.00"},
            {"currency": "NGN", "billing_cycle": BillingCycle.ANNUAL, "amount": "25000.00"},
        ],
    },
    {
        "category": "Storefront",
        "slug": "storefront",
        "feature": {
            "name": "Gift Cards",
            "code": "gift_cards",
            "feature_type": "boolean",
            "short_description": "Enable gift card support.",
            "description": "Turns on gift card storefront capability and related settings.",
            "store_setting_key": "enable_gift_cards",
            "icon": "redeem",
            "display_order": 100,
        },
        "prices": [
            {"currency": "NGN", "billing_cycle": BillingCycle.MONTHLY, "amount": "3500.00"},
            {"currency": "NGN", "billing_cycle": BillingCycle.ANNUAL, "amount": "35000.00"},
        ],
    },
    {
        "category": "Storefront",
        "slug": "storefront",
        "feature": {
            "name": "Subscriptions",
            "code": "subscriptions",
            "feature_type": "boolean",
            "short_description": "Enable subscription-style storefront selling.",
            "description": "Turns on subscription-oriented storefront behavior.",
            "store_setting_key": "enable_subscriptions",
            "icon": "subscriptions",
            "display_order": 110,
        },
        "prices": [
            {"currency": "NGN", "billing_cycle": BillingCycle.MONTHLY, "amount": "5000.00"},
            {"currency": "NGN", "billing_cycle": BillingCycle.ANNUAL, "amount": "50000.00"},
        ],
    },
    {
        "category": "Storefront",
        "slug": "storefront",
        "feature": {
            "name": "Live Chat",
            "code": "live_chat",
            "feature_type": "boolean",
            "short_description": "Enable live chat support prompts in the storefront.",
            "description": "Turns on the live chat storefront integration flag.",
            "store_setting_key": "enable_live_chat",
            "icon": "chat",
            "display_order": 120,
        },
        "prices": [
            {"currency": "NGN", "billing_cycle": BillingCycle.MONTHLY, "amount": "2500.00"},
            {"currency": "NGN", "billing_cycle": BillingCycle.ANNUAL, "amount": "25000.00"},
        ],
    },
    {
        "category": "Storefront",
        "slug": "storefront",
        "feature": {
            "name": "Discount Codes",
            "code": "discount_codes",
            "feature_type": "boolean",
            "short_description": "Unlock discount code management surfaces.",
            "description": "Enables discount-code storefront behavior and pricing dashboard access.",
            "store_setting_key": "enable_discount_codes",
            "storefront_flag": "enable_discount_codes",
            "sidebar_key": "pricing_discounts",
            "icon": "local_offer",
            "display_order": 130,
        },
        "prices": [
            {"currency": "NGN", "billing_cycle": BillingCycle.MONTHLY, "amount": "3000.00"},
            {"currency": "NGN", "billing_cycle": BillingCycle.ANNUAL, "amount": "30000.00"},
        ],
    },
    {
        "category": "Integrations",
        "slug": "integrations",
        "feature": {
            "name": "API Access",
            "code": "api_access",
            "feature_type": "boolean",
            "short_description": "Enable tenant API access.",
            "description": "Turns on the API-access premium toggle used by store settings and integration flows.",
            "store_setting_key": "enable_api_access",
            "icon": "api",
            "display_order": 140,
        },
        "prices": [
            {"currency": "NGN", "billing_cycle": BillingCycle.MONTHLY, "amount": "7000.00"},
            {"currency": "NGN", "billing_cycle": BillingCycle.ANNUAL, "amount": "70000.00"},
        ],
    },
    {
        "category": "Integrations",
        "slug": "integrations",
        "feature": {
            "name": "Webhooks",
            "code": "webhooks",
            "feature_type": "boolean",
            "short_description": "Enable outbound webhook integrations.",
            "description": "Turns on webhook-related settings and notification surfaces.",
            "store_setting_key": "enable_webhooks",
            "sidebar_key": "notification_webhooks",
            "icon": "webhook",
            "display_order": 150,
        },
        "prices": [
            {"currency": "NGN", "billing_cycle": BillingCycle.MONTHLY, "amount": "4500.00"},
            {"currency": "NGN", "billing_cycle": BillingCycle.ANNUAL, "amount": "45000.00"},
        ],
    },
    {
        "category": "Storefront",
        "slug": "storefront",
        "feature": {
            "name": "Social Login",
            "code": "social_login",
            "feature_type": "boolean",
            "short_description": "Enable social login options.",
            "description": "Turns on social login settings for storefront authentication.",
            "store_setting_key": "enable_social_login",
            "icon": "login",
            "display_order": 160,
        },
        "prices": [
            {"currency": "NGN", "billing_cycle": BillingCycle.MONTHLY, "amount": "2500.00"},
            {"currency": "NGN", "billing_cycle": BillingCycle.ANNUAL, "amount": "25000.00"},
        ],
    },
]


PLAN_BUNDLES = [
    {
        "slug": "starter-pack-monthly",
        "name": "Starter Pack Monthly",
        "description": "A clean launch package for new sellers who need a polished online storefront and simple operations.",
        "tagline": "Launch your store with the essentials.",
        "price": "5000.00",
        "currency": "NGN",
        "billing_cycle": BillingCycle.MONTHLY,
        "discount_percentage": "0.00",
        "is_featured": False,
        "display_order": 10,
        "items": [
            {"code": "max_products", "quantity_override": 50, "sort_order": 1},
            {"code": "reviews", "sort_order": 2},
            {"code": "wishlist", "sort_order": 3},
            {"code": "discount_codes", "sort_order": 4},
        ],
    },
    {
        "slug": "starter-pack-annual",
        "name": "Starter Pack Annual",
        "description": "A clean launch package for new sellers who need a polished online storefront and simple operations.",
        "tagline": "Two months free on annual billing.",
        "price": "50000.00",
        "currency": "NGN",
        "billing_cycle": BillingCycle.ANNUAL,
        "discount_percentage": "16.67",
        "is_featured": False,
        "display_order": 11,
        "items": [
            {"code": "max_products", "quantity_override": 50, "sort_order": 1},
            {"code": "reviews", "sort_order": 2},
            {"code": "wishlist", "sort_order": 3},
            {"code": "discount_codes", "sort_order": 4},
        ],
    },
    {
        "slug": "premium-pack-monthly",
        "name": "Premium Pack Monthly",
        "description": "The best fit for growing stores that need stronger merchandising, reports, domains, and team access.",
        "tagline": "Most popular for serious online sellers.",
        "price": "15000.00",
        "currency": "NGN",
        "billing_cycle": BillingCycle.MONTHLY,
        "discount_percentage": "0.00",
        "is_featured": True,
        "display_order": 20,
        "items": [
            {"code": "max_products", "quantity_override": 250, "sort_order": 1},
            {"code": "advanced_analytics", "sort_order": 2},
            {"code": "advanced_reports", "sort_order": 3},
            {"code": "staff_management", "quantity_override": 5, "sort_order": 4},
            {"code": "max_custom_domains", "quantity_override": 1, "sort_order": 5},
            {"code": "compare", "sort_order": 6},
            {"code": "live_chat", "sort_order": 7},
        ],
    },
    {
        "slug": "premium-pack-annual",
        "name": "Premium Pack Annual",
        "description": "The best fit for growing stores that need stronger merchandising, reports, domains, and team access.",
        "tagline": "Two months free on annual billing.",
        "price": "150000.00",
        "currency": "NGN",
        "billing_cycle": BillingCycle.ANNUAL,
        "discount_percentage": "16.67",
        "is_featured": True,
        "display_order": 21,
        "items": [
            {"code": "max_products", "quantity_override": 250, "sort_order": 1},
            {"code": "advanced_analytics", "sort_order": 2},
            {"code": "advanced_reports", "sort_order": 3},
            {"code": "staff_management", "quantity_override": 5, "sort_order": 4},
            {"code": "max_custom_domains", "quantity_override": 1, "sort_order": 5},
            {"code": "compare", "sort_order": 6},
            {"code": "live_chat", "sort_order": 7},
        ],
    },
    {
        "slug": "pro-pack-monthly",
        "name": "Pro Pack Monthly",
        "description": "A complete commerce workspace for stores with POS, automation, integrations, and higher-volume operations.",
        "tagline": "For brands ready to run the full stack.",
        "price": "35000.00",
        "currency": "NGN",
        "billing_cycle": BillingCycle.MONTHLY,
        "discount_percentage": "0.00",
        "is_featured": False,
        "display_order": 30,
        "items": [
            {"code": "max_products", "quantity_override": 1000, "sort_order": 1},
            {"code": "max_pos_locations", "quantity_override": 2, "sort_order": 2},
            {"code": "staff_management", "quantity_override": 15, "sort_order": 3},
            {"code": "max_custom_domains", "quantity_override": 2, "sort_order": 4},
            {"code": "gift_cards", "sort_order": 5},
            {"code": "subscriptions", "sort_order": 6},
            {"code": "api_access", "sort_order": 7},
            {"code": "webhooks", "sort_order": 8},
            {"code": "social_login", "sort_order": 9},
            {"code": "ai_credits", "quantity_override": 25000, "sort_order": 10},
        ],
    },
    {
        "slug": "pro-pack-annual",
        "name": "Pro Pack Annual",
        "description": "A complete commerce workspace for stores with POS, automation, integrations, and higher-volume operations.",
        "tagline": "Two months free on annual billing.",
        "price": "350000.00",
        "currency": "NGN",
        "billing_cycle": BillingCycle.ANNUAL,
        "discount_percentage": "16.67",
        "is_featured": False,
        "display_order": 31,
        "items": [
            {"code": "max_products", "quantity_override": 1000, "sort_order": 1},
            {"code": "max_pos_locations", "quantity_override": 2, "sort_order": 2},
            {"code": "staff_management", "quantity_override": 15, "sort_order": 3},
            {"code": "max_custom_domains", "quantity_override": 2, "sort_order": 4},
            {"code": "gift_cards", "sort_order": 5},
            {"code": "subscriptions", "sort_order": 6},
            {"code": "api_access", "sort_order": 7},
            {"code": "webhooks", "sort_order": 8},
            {"code": "social_login", "sort_order": 9},
            {"code": "ai_credits", "quantity_override": 300000, "sort_order": 10},
        ],
    },
]

PLAN_BUNDLE_SLUGS = tuple(item["slug"] for item in PLAN_BUNDLES)
STALE_PLAN_BUNDLE_SLUGS = (
    "beginner",
    "pro",
    "premium",
    "enterprise",
    "storefront-plus",
    "operations-plus",
    "integrations-plus",
    "growth-pack-annual",
    "ai-credit-booster",
    "ai-credit-studio",
)
STALE_PLAN_CAMPAIGN_NAMES = (
    "Marketplace Launch",
)

REALISTIC_PLUS_BUNDLES = PLAN_BUNDLES


REALISTIC_PLUS_CAMPAIGNS = [
    {
        "name": "Plan Launch",
        "description": "Introductory launch campaign across the active Starter, Premium, and Pro packs.",
        "discount_type": DiscountType.PERCENTAGE,
        "discount_value": "10.00",
        "feature_codes": ["advanced_analytics", "advanced_reports", "reviews", "wishlist"],
        "bundle_slugs": ["starter-pack-monthly", "premium-pack-monthly", "pro-pack-monthly"],
    },
]


REALISTIC_PLUS_COUPONS = [
    {
        "code": "STORE20",
        "description": "20 percent off Starter and Premium launch plans.",
        "discount_type": DiscountType.PERCENTAGE,
        "discount_value": "20.00",
        "bundle_slugs": ["starter-pack-monthly", "premium-pack-monthly"],
        "max_uses": 200,
        "max_uses_per_tenant": 3,
    },
    {
        "code": "AIBOOST1500",
        "description": "Fixed discount for Pro plan checkout testing.",
        "discount_type": DiscountType.FIXED,
        "discount_value": "1500.00",
        "bundle_slugs": ["pro-pack-monthly", "pro-pack-annual"],
        "max_uses": 150,
        "max_uses_per_tenant": 2,
    },
    {
        "code": "STACKUP",
        "description": "Bundle and analytics upgrade coupon for realistic checkout tests.",
        "discount_type": DiscountType.FIXED,
        "discount_value": "2500.00",
        "feature_codes": ["advanced_analytics", "advanced_reports"],
        "bundle_slugs": ["premium-pack-monthly", "premium-pack-annual", "pro-pack-monthly", "pro-pack-annual"],
        "max_uses": 250,
        "max_uses_per_tenant": 4,
    },
]


CATALOG_PROFILES = {
    "starter": {
        "features": STARTER_FEATURES,
        "bundles": [],
        "campaigns": [],
        "coupons": [],
    },
    "realistic-plus": {
        "features": REALISTIC_PLUS_FEATURES,
        "bundles": REALISTIC_PLUS_BUNDLES,
        "campaigns": REALISTIC_PLUS_CAMPAIGNS,
        "coupons": REALISTIC_PLUS_COUPONS,
    },
}


RESERVED_FUTURE_FEATURES = (
    {
        "code": "product_scraper",
        "feature_type": "boolean",
        "seed_in_catalog": False,
        "note": "Future module unlock for catalog scraping/import workflows.",
    },
    {
        "code": "import_credits",
        "feature_type": "usage",
        "seed_in_catalog": False,
        "note": "Future usage-credit pool for import jobs and assisted scraping.",
    },
    {
        "code": "scrape_jobs",
        "feature_type": "limit",
        "seed_in_catalog": False,
        "note": "Future quota for scheduled scrape/import job capacity.",
    },
)
