# Generated by Django 5.2 on 2026-04-14 15:38

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VisitorSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_key', models.CharField(db_index=True, max_length=64)),
                ('schema_name', models.CharField(db_index=True, default='public', max_length=63)),
                ('source', models.CharField(choices=[('storefront', 'Storefront'), ('dashboard', 'Dashboard'), ('platform', 'Platform'), ('unknown', 'Unknown')], db_index=True, default='unknown', max_length=20)),
                ('user_identifier', models.CharField(blank=True, db_index=True, max_length=128)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('referrer', models.URLField(blank=True)),
                ('landing_path', models.CharField(blank=True, max_length=500)),
                ('last_path', models.CharField(blank=True, max_length=500)),
                ('is_bot', models.BooleanField(default=False)),
                ('visit_count', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('last_seen_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-last_seen_at'],
                'indexes': [models.Index(fields=['schema_name', 'source', 'last_seen_at'], name='monitoring__schema__168e8c_idx')],
            },
        ),
        migrations.CreateModel(
            name='PageVisit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('schema_name', models.CharField(db_index=True, default='public', max_length=63)),
                ('source', models.CharField(choices=[('storefront', 'Storefront'), ('dashboard', 'Dashboard'), ('platform', 'Platform'), ('unknown', 'Unknown')], db_index=True, default='unknown', max_length=20)),
                ('path', models.CharField(db_index=True, max_length=500)),
                ('full_url', models.URLField(blank=True)),
                ('route_name', models.CharField(blank=True, db_index=True, max_length=255)),
                ('method', models.CharField(default='GET', max_length=10)),
                ('referrer', models.URLField(blank=True)),
                ('status_code', models.PositiveSmallIntegerField(db_index=True, default=200)),
                ('server_duration_ms', models.PositiveIntegerField(default=0)),
                ('client_duration_ms', models.PositiveIntegerField(default=0)),
                ('engaged_seconds', models.PositiveIntegerField(default=0)),
                ('page_title', models.CharField(blank=True, max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('visitor_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_visits', to='monitoring.visitorsession')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['schema_name', 'source', 'created_at'], name='monitoring__schema__14e4a4_idx'), models.Index(fields=['path', 'created_at'], name='monitoring__path_be0e12_idx')],
            },
        ),
    ]
