# Generated by Django 5.2 on 2026-04-04 15:40

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
        ('pos', '0001_initial'),
        ('product', '0002_initial'),
        ('userauth', '0002_alter_permission_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='postransaction',
            name='authoritative_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pos_transactions', to='cart.order'),
        ),
        migrations.AlterField(
            model_name='storeinventory',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='store_inventory', to='pos.posproduct'),
        ),
        migrations.CreateModel(
            name='POSCatalogItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Date and time when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Date and time when this record was last modified')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Date and time when this record was deleted', null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Whether this record is soft-deleted')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label_override', models.CharField(blank=True, max_length=255)),
                ('barcode_override', models.CharField(blank=True, db_index=True, max_length=100)),
                ('quick_add_code', models.CharField(blank=True, db_index=True, max_length=50)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('allow_open_quantity', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to='userauth.tenantuser')),
                ('deleted_by', models.ForeignKey(blank=True, help_text='User who deleted this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to='userauth.tenantuser')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pos_catalog_items', to='product.product')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last modified this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to='userauth.tenantuser')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pos_catalog_items', to='product.productvariant')),
            ],
            options={
                'db_table': 'pos_catalog_items',
                'ordering': ['product__name', 'variant__sku'],
                'unique_together': {('product', 'variant')},
            },
        ),
        migrations.AddField(
            model_name='postransactionitem',
            name='catalog_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction_items', to='pos.poscatalogitem'),
        ),
        migrations.AddField(
            model_name='storeinventory',
            name='catalog_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_records', to='pos.poscatalogitem'),
        ),
        migrations.CreateModel(
            name='POSSession',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Date and time when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Date and time when this record was last modified')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Date and time when this record was deleted', null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Whether this record is soft-deleted')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], db_index=True, default='open', max_length=20)),
                ('opened_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('opening_cash', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('closing_cash', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('notes', models.TextField(blank=True)),
                ('cashier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pos_sessions', to='userauth.tenantuser')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to='userauth.tenantuser')),
                ('deleted_by', models.ForeignKey(blank=True, help_text='User who deleted this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to='userauth.tenantuser')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='pos.store')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last modified this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to='userauth.tenantuser')),
            ],
            options={
                'db_table': 'pos_sessions',
                'ordering': ['-opened_at'],
            },
        ),
        migrations.AddField(
            model_name='postransaction',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='pos.possession'),
        ),
        migrations.CreateModel(
            name='POSTerminal',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Date and time when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Date and time when this record was last modified')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Date and time when this record was deleted', null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Whether this record is soft-deleted')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('terminal_type', models.CharField(choices=[('browser', 'Browser / Web POS'), ('escpos', 'ESC/POS Printer'), ('network', 'Network Printer')], default='browser', max_length=20)),
                ('printer_identifier', models.CharField(blank=True, max_length=255)),
                ('receipt_header', models.TextField(blank=True)),
                ('receipt_footer', models.TextField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to='userauth.tenantuser')),
                ('deleted_by', models.ForeignKey(blank=True, help_text='User who deleted this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to='userauth.tenantuser')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terminals', to='pos.store')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last modified this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to='userauth.tenantuser')),
            ],
            options={
                'db_table': 'pos_terminals',
                'ordering': ['store__name', 'name'],
            },
        ),
        migrations.AddField(
            model_name='possession',
            name='terminal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='pos.posterminal'),
        ),
        migrations.AddField(
            model_name='postransaction',
            name='terminal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='pos.posterminal'),
        ),
    ]
