# Generated by Django 5.2 on 2026-04-04 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0002_postransaction_authoritative_order_and_more'),
        ('userauth', '0002_alter_permission_category'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='storeinventory',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='storeinventory',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('product__isnull', False), ('catalog_item__isnull', True)), models.Q(('product__isnull', True), ('catalog_item__isnull', False)), _connector='OR'), name='pos_inventory_requires_one_item_source'),
        ),
        migrations.AddConstraint(
            model_name='storeinventory',
            constraint=models.UniqueConstraint(condition=models.Q(('product__isnull', False)), fields=('store', 'product'), name='pos_unique_store_legacy_product'),
        ),
        migrations.AddConstraint(
            model_name='storeinventory',
            constraint=models.UniqueConstraint(condition=models.Q(('catalog_item__isnull', False)), fields=('store', 'catalog_item'), name='pos_unique_store_catalog_item'),
        ),
    ]
