# Generated by Django 5.2 on 2026-04-20 21:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0005_poscart_poscartitem'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='poscart',
            new_name='pos_cart_cashier_b5c606_idx',
            old_name='pos_cart_cashier_store_status_idx',
        ),
        migrations.RenameIndex(
            model_name='poscart',
            new_name='pos_cart_store_i_aa87b2_idx',
            old_name='pos_cart_store_status_idx',
        ),
        migrations.AlterField(
            model_name='poscart',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='poscart',
            name='session_id',
            field=models.UUIDField(blank=True, help_text='UUID of the related POSSession (soft reference — no DB-level FK constraint).', null=True, verbose_name='Session ID'),
        ),
        migrations.AlterField(
            model_name='poscartitem',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
