# Generated by Django 5.2 on 2026-04-27 13:43

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0006_rename_pos_cart_cashier_store_status_idx_pos_cart_cashier_b5c606_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='poscart',
            name='held_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='poscart',
            name='hold_reference',
            field=models.CharField(blank=True, db_index=True, max_length=80),
        ),
        migrations.AddField(
            model_name='pospayment',
            name='amount_received',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='pospayment',
            name='balance_returned',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='pospayment',
            name='bank_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='pospayment',
            name='custom_payment_label',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='pospayment',
            name='terminal_reference',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='possession',
            name='expected_cash',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='possession',
            name='overage_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='possession',
            name='shortage_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='posterminal',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='postransaction',
            name='client_transaction_id',
            field=models.CharField(blank=True, db_index=True, max_length=80),
        ),
        migrations.AddField(
            model_name='postransaction',
            name='origin_mode',
            field=models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('synced', 'Synced Offline')], db_index=True, default='online', max_length=20),
        ),
        migrations.AddField(
            model_name='postransaction',
            name='refunded_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='postransaction',
            name='sync_status',
            field=models.CharField(choices=[('not_required', 'Not Required'), ('queued', 'Queued'), ('synced', 'Synced'), ('failed', 'Failed')], db_index=True, default='not_required', max_length=20),
        ),
        migrations.AddField(
            model_name='store',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='store',
            name='contact_name',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='store',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='store',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('maintenance', 'Maintenance')], db_index=True, default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='poscart',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('held', 'Held'), ('completed', 'Completed'), ('voided', 'Voided')], db_index=True, default='open', max_length=12),
        ),
        migrations.AlterField(
            model_name='pospayment',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('card_terminal', 'POS Terminal / Card'), ('split', 'Split Payment'), ('mobile_money', 'Mobile Money'), ('custom', 'Custom Payment Method')], db_index=True, max_length=20),
        ),
    ]
