# Generated by Django 5.2 on 2026-04-04 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='category',
            field=models.CharField(choices=[('dashboard', 'Dashboard'), ('products', 'Products'), ('attribute_groups', 'Attribute Groups'), ('attributes', 'Attributes'), ('categories', 'Categories'), ('brands', 'Brands'), ('tags', 'Tags'), ('pricing', 'Pricing & Promotions'), ('pos', 'Point of Sale'), ('payments', 'Payments'), ('marketplace', 'Marketplace'), ('domains', 'Domains & SSL'), ('notifications', 'Notifications'), ('settings', 'Storefront & Settings'), ('users', 'Users'), ('staff', 'Store Staff'), ('roles', 'Roles & Permissions'), ('customers', 'Customers'), ('audit', 'Audit & Compliance')], db_index=True, max_length=20),
        ),
    ]
