# Generated by Django 5.2 on 2026-03-28 01:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentGatewayDefinition',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('paystack', 'Paystack'), ('flutterwave', 'Flutterwave'), ('stripe', 'Stripe'), ('paypal', 'PayPal'), ('square', 'Square'), ('braintree', 'Braintree'), ('razorpay', 'Razorpay'), ('monnify', 'Monnify'), ('interswitch', 'Interswitch'), ('opay', 'OPay'), ('moniepoint', 'Moniepoint'), ('manual', 'Manual / Bank Transfer'), ('cod', 'Cash on Delivery'), ('crypto', 'Cryptocurrency')], db_index=True, max_length=20, unique=True, verbose_name='Provider')),
                ('name', models.CharField(max_length=100, verbose_name='Display Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('logo_url', models.URLField(blank=True, verbose_name='Logo URL')),
                ('website_url', models.URLField(blank=True, verbose_name='Website')),
                ('documentation_url', models.URLField(blank=True, verbose_name='API Docs')),
                ('dashboard_url', models.URLField(blank=True, verbose_name='Provider Dashboard URL')),
                ('is_enabled', models.BooleanField(db_index=True, default=False, verbose_name='Enabled on Platform')),
                ('is_available_for_direct_mode', models.BooleanField(default=True, verbose_name='Available for Direct Mode')),
                ('requires_business_verification', models.BooleanField(default=False, verbose_name='Requires KYB for Direct Mode')),
                ('supported_countries', models.JSONField(default=list, verbose_name='Supported Countries')),
                ('supported_currencies', models.JSONField(default=list, verbose_name='Supported Currencies')),
                ('supports_recurring', models.BooleanField(default=False, verbose_name='Recurring')),
                ('supports_refunds', models.BooleanField(default=True, verbose_name='Refunds')),
                ('supports_partial_refunds', models.BooleanField(default=False, verbose_name='Partial Refunds')),
                ('supports_tokenization', models.BooleanField(default=False, verbose_name='Tokenization')),
                ('supports_3ds', models.BooleanField(default=False, verbose_name='3D Secure')),
                ('supports_split_payment', models.BooleanField(default=False, help_text='Paystack/Flutterwave subaccount-based revenue splitting.', verbose_name='Native Split Payment')),
                ('supports_virtual_accounts', models.BooleanField(default=False, verbose_name='Virtual Accounts')),
                ('supports_authorization', models.BooleanField(default=False, verbose_name='Authorize & Capture')),
                ('min_transaction_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Min Transaction')),
                ('max_transaction_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Max Transaction')),
                ('settlement_days', models.PositiveSmallIntegerField(default=1, verbose_name='Settlement Days T+N')),
                ('settlement_note', models.CharField(blank=True, max_length=255, verbose_name='Settlement Note')),
                ('credential_schema', models.JSONField(default=dict, verbose_name='Credential Schema')),
                ('webhook_events', models.JSONField(default=list, verbose_name='Webhook Events')),
                ('display_order', models.PositiveSmallIntegerField(default=0, verbose_name='Display Order')),
                ('badge_label', models.CharField(blank=True, max_length=50, verbose_name='Badge Label')),
            ],
            options={
                'verbose_name': 'Payment Gateway Definition',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='GatewayWebhookConfig',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('webhook_url', models.URLField(verbose_name='Platform Webhook URL')),
                ('signature_header', models.CharField(blank=True, max_length=100, verbose_name='Signature Header')),
                ('signature_algorithm', models.CharField(choices=[('hmac_sha256', 'HMAC-SHA256'), ('hmac_sha512', 'HMAC-SHA512')], default='hmac_sha256', max_length=20, verbose_name='Algorithm')),
                ('ip_whitelist', models.JSONField(blank=True, default=list, verbose_name='Allowed IPs')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('last_received_at', models.DateTimeField(blank=True, null=True, verbose_name='Last Event At')),
                ('total_events_received', models.PositiveIntegerField(default=0, verbose_name='Total Events')),
                ('gateway', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='webhook_config', to='system_pay.paymentgatewaydefinition')),
            ],
            options={
                'verbose_name': 'Gateway Webhook Config',
            },
        ),
        migrations.CreateModel(
            name='PlatformGatewayCredential',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('environment', models.CharField(choices=[('test', 'Test'), ('live', 'Live')], db_index=True, default='test', max_length=5, verbose_name='Environment')),
                ('is_active', models.BooleanField(db_index=True, default=False, verbose_name='Active')),
                ('priority', models.PositiveIntegerField(default=0, verbose_name='Priority')),
                ('public_key', models.TextField(blank=True, verbose_name='Public Key (encrypted)')),
                ('secret_key', models.TextField(verbose_name='Secret Key (encrypted)')),
                ('encryption_key', models.TextField(blank=True, verbose_name='Encryption Key (encrypted)')),
                ('webhook_secret', models.TextField(blank=True, verbose_name='Webhook Secret (encrypted)')),
                ('extra_credentials', models.JSONField(blank=True, default=dict, verbose_name='Extra Credentials (encrypted)')),
                ('account_id', models.CharField(blank=True, max_length=255, verbose_name='Platform Account ID')),
                ('subaccount_code', models.CharField(blank=True, help_text='For revenue splitting: platform receives commission here.', max_length=255, verbose_name='Platform Master Subaccount Code')),
                ('daily_transaction_limit', models.PositiveIntegerField(blank=True, null=True, verbose_name='Daily Limit')),
                ('monthly_volume_limit', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Monthly Volume Limit')),
                ('supported_countries', models.JSONField(blank=True, default=list, verbose_name='Countries')),
                ('default_currency', models.CharField(default='NGN', max_length=3, verbose_name='Default Currency')),
                ('last_used_at', models.DateTimeField(blank=True, null=True, verbose_name='Last Used')),
                ('last_health_check_at', models.DateTimeField(blank=True, null=True, verbose_name='Last Health Check')),
                ('is_healthy', models.BooleanField(default=True, verbose_name='Healthy')),
                ('health_note', models.CharField(blank=True, max_length=500, verbose_name='Health Note')),
                ('gateway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platform_credentials', to='system_pay.paymentgatewaydefinition')),
            ],
            options={
                'verbose_name': 'Platform Gateway Credential',
                'ordering': ['-priority', 'gateway__name'],
                'indexes': [models.Index(fields=['gateway', 'environment', 'is_active'], name='system_pay__gateway_de20ac_idx')],
            },
        ),
    ]
