# Generated by Django 5.2 on 2026-03-26 12:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0002_initial'),
        ('pricing', '0001_initial'),
        ('product', '0001_initial'),
        ('userauth', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='automaticdiscount',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to='userauth.tenantuser'),
        ),
        migrations.AddField(
            model_name='automaticdiscount',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='User who deleted this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to='userauth.tenantuser'),
        ),
        migrations.AddField(
            model_name='automaticdiscount',
            name='free_item_variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='automatic_free_item_discounts', to='product.productvariant'),
        ),
        migrations.AddField(
            model_name='automaticdiscount',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='User who last modified this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to='userauth.tenantuser'),
        ),
        migrations.AddField(
            model_name='automaticdiscountbenefit',
            name='automatic_discount',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benefits', to='pricing.automaticdiscount', verbose_name='Automatic Discount'),
        ),
        migrations.AddField(
            model_name='automaticdiscountbenefit',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='automatic_discount_benefits', to='product.product'),
        ),
        migrations.AddField(
            model_name='automaticdiscountcondition',
            name='automatic_discount',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='pricing.automaticdiscount', verbose_name='Automatic Discount'),
        ),
        migrations.AddField(
            model_name='automaticdiscountcondition',
            name='customer_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='automatic_discount_conditions', to='userauth.customergroup'),
        ),
        migrations.AddField(
            model_name='automaticdiscountcondition',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='automatic_discount_conditions', to='product.product'),
        ),
        migrations.AddField(
            model_name='buyxgetyitem',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bxgy_items', to='category.category'),
        ),
        migrations.AddField(
            model_name='buyxgetyitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bxgy_items', to='product.product'),
        ),
        migrations.AddField(
            model_name='buyxgetyitem',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bxgy_items', to='product.productvariant'),
        ),
        migrations.AddField(
            model_name='buyxgetypromotion',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to='userauth.tenantuser'),
        ),
        migrations.AddField(
            model_name='buyxgetypromotion',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='User who deleted this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to='userauth.tenantuser'),
        ),
        migrations.AddField(
            model_name='buyxgetypromotion',
            name='get_specific_variant',
            field=models.ForeignKey(blank=True, help_text='For SPECIFIC_VARIANT get type.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bxgy_get_promotions', to='product.productvariant', verbose_name='Free/Discounted Variant'),
        ),
        migrations.AddField(
            model_name='buyxgetypromotion',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='User who last modified this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to='userauth.tenantuser'),
        ),
        migrations.AddField(
            model_name='buyxgetyitem',
            name='promotion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pricing.buyxgetypromotion', verbose_name='Promotion'),
        ),
        migrations.AddField(
            model_name='automaticdiscount',
            name='buy_x_get_y_promotion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='automatic_triggers', to='pricing.buyxgetypromotion'),
        ),
        migrations.AddField(
            model_name='discountcode',
            name='buy_x_get_y_promotion',
            field=models.ForeignKey(blank=True, help_text='For BUY_X_GET_Y type: the promotion triggered by this code.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trigger_codes', to='pricing.buyxgetypromotion', verbose_name='Buy X Get Y Promotion'),
        ),
        migrations.AddField(
            model_name='discountcode',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to='userauth.tenantuser'),
        ),
        migrations.AddField(
            model_name='discountcode',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='User who deleted this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to='userauth.tenantuser'),
        ),
        migrations.AddField(
            model_name='discountcode',
            name='free_item_variant',
            field=models.ForeignKey(blank=True, help_text='For FREE_ITEM type: the variant added to the cart for free.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='free_item_discounts', to='product.productvariant', verbose_name='Free Item Variant'),
        ),
        migrations.AddField(
            model_name='discountcode',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='User who last modified this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to='userauth.tenantuser'),
        ),
        migrations.AddField(
            model_name='discountrule',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discount_rules', to='category.category'),
        ),
        migrations.AddField(
            model_name='discountrule',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discount_rules', to='userauth.customer'),
        ),
        migrations.AddField(
            model_name='discountrule',
            name='customer_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discount_rules', to='userauth.customergroup'),
        ),
        migrations.AddField(
            model_name='discountrule',
            name='discount_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='pricing.discountcode', verbose_name='Discount Code'),
        ),
        migrations.AddField(
            model_name='discountrule',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discount_rules', to='product.product'),
        ),
        migrations.AddField(
            model_name='discountrule',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discount_rules', to='product.productvariant'),
        ),
        migrations.AddField(
            model_name='discountusage',
            name='customer',
            field=models.ForeignKey(blank=True, help_text='Null for guest checkouts.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discount_usages', to='userauth.customer', verbose_name='Customer'),
        ),
        migrations.AddField(
            model_name='discountusage',
            name='discount_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='pricing.discountcode', verbose_name='Discount Code'),
        ),
        migrations.AddField(
            model_name='exchangerate',
            name='base_currency',
            field=models.ForeignKey(help_text='The currency being converted FROM (usually the store base).', on_delete=django.db.models.deletion.CASCADE, related_name='base_rates', to='pricing.currency', verbose_name='Base Currency'),
        ),
        migrations.AddField(
            model_name='exchangerate',
            name='target_currency',
            field=models.ForeignKey(help_text='The currency being converted TO.', on_delete=django.db.models.deletion.CASCADE, related_name='target_rates', to='pricing.currency', verbose_name='Target Currency'),
        ),
        migrations.AddField(
            model_name='flashsale',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_flash_sales', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='flashsaleitem',
            name='flash_sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pricing.flashsale', verbose_name='Flash Sale'),
        ),
        migrations.AddField(
            model_name='flashsaleitem',
            name='product',
            field=models.ForeignKey(blank=True, help_text='If set (without variant), applies to all variants of this public.product.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flash_sale_items', to='product.product'),
        ),
        migrations.AddField(
            model_name='flashsaleitem',
            name='variant',
            field=models.ForeignKey(blank=True, help_text='Specific variant override. Takes precedence over product-level entry.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flash_sale_items', to='product.productvariant'),
        ),
        migrations.AddField(
            model_name='giftcard',
            name='issued_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_gift_cards', to=settings.AUTH_USER_MODEL, verbose_name='Issued By (Staff)'),
        ),
        migrations.AddField(
            model_name='giftcard',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='The customer who currently has this card in their account.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gift_cards', to='userauth.customer', verbose_name='Card Owner (Customer)'),
        ),
        migrations.AddField(
            model_name='giftcard',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_cards', to='pricing.giftcardtemplate', verbose_name='Template'),
        ),
        migrations.AddField(
            model_name='giftcardtransaction',
            name='gift_card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='pricing.giftcard', verbose_name='Gift Card'),
        ),
        migrations.AddField(
            model_name='giftcardtransaction',
            name='related_card',
            field=models.ForeignKey(blank=True, help_text='For TRANSFER transactions: the other card involved.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_transactions', to='pricing.giftcard', verbose_name='Related Gift Card'),
        ),
        migrations.AddField(
            model_name='pricelist',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to='userauth.tenantuser'),
        ),
        migrations.AddField(
            model_name='pricelist',
            name='currency',
            field=models.ForeignKey(blank=True, help_text='If set, prices in this list are in this currency. Null = use store base currency.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='price_lists', to='pricing.currency', verbose_name='Currency'),
        ),
        migrations.AddField(
            model_name='pricelist',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='User who deleted this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to='userauth.tenantuser'),
        ),
        migrations.AddField(
            model_name='pricelist',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='User who last modified this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to='userauth.tenantuser'),
        ),
        migrations.AddField(
            model_name='pricelistcustomergroup',
            name='assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='price_list_assignments_made', to='userauth.tenantuser'),
        ),
        migrations.AddField(
            model_name='pricelistcustomergroup',
            name='customer',
            field=models.ForeignKey(blank=True, help_text='Assign the price list to a specific customer (overrides group assignment).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='price_list_assignments', to='userauth.customer', verbose_name='Individual Customer'),
        ),
        migrations.AddField(
            model_name='pricelistcustomergroup',
            name='customer_group',
            field=models.ForeignKey(blank=True, help_text='Assign the price list to a customer group.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='price_list_assignments', to='userauth.customergroup', verbose_name='Customer Group'),
        ),
        migrations.AddField(
            model_name='pricelistcustomergroup',
            name='price_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_group_assignments', to='pricing.pricelist', verbose_name='Price List'),
        ),
        migrations.AddField(
            model_name='pricelistentry',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Applied to all products in this category if no product/variant set.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='price_list_entries', to='category.category', verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='pricelistentry',
            name='price_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='pricing.pricelist', verbose_name='Price List'),
        ),
        migrations.AddField(
            model_name='pricelistentry',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='price_list_entries', to='product.product', verbose_name='Product'),
        ),
        migrations.AddField(
            model_name='pricelistentry',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='price_list_entries', to='product.productvariant', verbose_name='Variant'),
        ),
        migrations.AddField(
            model_name='taxrate',
            name='tax_category',
            field=models.ForeignKey(help_text='The product classification this rate applies to within the zone.', on_delete=django.db.models.deletion.CASCADE, related_name='tax_rates', to='pricing.taxcategory', verbose_name='Tax Category'),
        ),
        migrations.AddIndex(
            model_name='taxzone',
            index=models.Index(fields=['code'], name='pricing_tax_code_da6d0e_idx'),
        ),
        migrations.AddIndex(
            model_name='taxzone',
            index=models.Index(fields=['zone_type', 'is_active'], name='pricing_tax_zone_ty_97e46d_idx'),
        ),
        migrations.AddIndex(
            model_name='taxzone',
            index=models.Index(fields=['priority'], name='pricing_tax_priorit_5f7156_idx'),
        ),
        migrations.AddField(
            model_name='taxrate',
            name='tax_zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_rates', to='pricing.taxzone', verbose_name='Tax Zone'),
        ),
        migrations.AddField(
            model_name='volumepricingtier',
            name='customer_group',
            field=models.ForeignKey(blank=True, help_text='If set, this tier only applies to customers in this group. Null = applies to all customers.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='volume_tiers', to='userauth.customergroup', verbose_name='Customer Group'),
        ),
        migrations.AddField(
            model_name='volumepricingtier',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volume_tiers', to='product.productvariant', verbose_name='Product Variant'),
        ),
        migrations.AddIndex(
            model_name='buyxgetypromotion',
            index=models.Index(fields=['is_active', 'starts_at', 'ends_at'], name='pricing_buy_is_acti_d3f8f0_idx'),
        ),
        migrations.AddIndex(
            model_name='automaticdiscount',
            index=models.Index(fields=['is_active', 'starts_at', 'ends_at'], name='pricing_aut_is_acti_d264e1_idx'),
        ),
        migrations.AddIndex(
            model_name='automaticdiscount',
            index=models.Index(fields=['priority', 'is_active'], name='pricing_aut_priorit_30900e_idx'),
        ),
        migrations.AddIndex(
            model_name='discountcode',
            index=models.Index(fields=['code'], name='pricing_dis_code_b2ef5b_idx'),
        ),
        migrations.AddIndex(
            model_name='discountcode',
            index=models.Index(fields=['is_active', 'starts_at', 'ends_at'], name='pricing_dis_is_acti_8181a3_idx'),
        ),
        migrations.AddIndex(
            model_name='discountcode',
            index=models.Index(fields=['value_type', 'scope'], name='pricing_dis_value_t_302281_idx'),
        ),
        migrations.AddIndex(
            model_name='discountcode',
            index=models.Index(fields=['usage_count'], name='pricing_dis_usage_c_40a8cd_idx'),
        ),
        migrations.AddIndex(
            model_name='discountrule',
            index=models.Index(fields=['discount_code', 'rule_type'], name='pricing_dis_discoun_ea9f7b_idx'),
        ),
        migrations.AddIndex(
            model_name='discountusage',
            index=models.Index(fields=['discount_code', 'customer'], name='pricing_dis_discoun_3bc50b_idx'),
        ),
        migrations.AddIndex(
            model_name='discountusage',
            index=models.Index(fields=['discount_code', '-used_at'], name='pricing_dis_discoun_585085_idx'),
        ),
        migrations.AddIndex(
            model_name='discountusage',
            index=models.Index(fields=['order_id'], name='pricing_dis_order_i_0c2d77_idx'),
        ),
        migrations.AddIndex(
            model_name='discountusage',
            index=models.Index(fields=['customer_email'], name='pricing_dis_custome_2cccf2_idx'),
        ),
        migrations.AddIndex(
            model_name='discountusage',
            index=models.Index(fields=['ip_address'], name='pricing_dis_ip_addr_2583ee_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='exchangerate',
            unique_together={('base_currency', 'target_currency')},
        ),
        migrations.AddIndex(
            model_name='flashsale',
            index=models.Index(fields=['is_active', 'starts_at', 'ends_at'], name='pricing_fla_is_acti_e6d510_idx'),
        ),
        migrations.AddIndex(
            model_name='flashsale',
            index=models.Index(fields=['slug'], name='pricing_fla_slug_c88281_idx'),
        ),
        migrations.AddIndex(
            model_name='flashsale',
            index=models.Index(fields=['is_publicly_visible', 'is_active'], name='pricing_fla_is_publ_3ec16d_idx'),
        ),
        migrations.AddIndex(
            model_name='flashsaleitem',
            index=models.Index(fields=['flash_sale', 'is_active'], name='pricing_fla_flash_s_b3274f_idx'),
        ),
        migrations.AddIndex(
            model_name='flashsaleitem',
            index=models.Index(fields=['variant'], name='pricing_fla_variant_b28ead_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='flashsaleitem',
            unique_together={('flash_sale', 'product'), ('flash_sale', 'variant')},
        ),
        migrations.AddIndex(
            model_name='giftcard',
            index=models.Index(fields=['code'], name='pricing_gif_code_ee9442_idx'),
        ),
        migrations.AddIndex(
            model_name='giftcard',
            index=models.Index(fields=['status', 'expires_at'], name='pricing_gif_status_554fc0_idx'),
        ),
        migrations.AddIndex(
            model_name='giftcard',
            index=models.Index(fields=['owner'], name='pricing_gif_owner_i_a1048e_idx'),
        ),
        migrations.AddIndex(
            model_name='giftcard',
            index=models.Index(fields=['recipient_email'], name='pricing_gif_recipie_8888ec_idx'),
        ),
        migrations.AddIndex(
            model_name='giftcard',
            index=models.Index(fields=['purchase_order_id'], name='pricing_gif_purchas_603fcf_idx'),
        ),
        migrations.AddIndex(
            model_name='giftcardtransaction',
            index=models.Index(fields=['gift_card', '-created_at'], name='pricing_gif_gift_ca_5f1db7_idx'),
        ),
        migrations.AddIndex(
            model_name='giftcardtransaction',
            index=models.Index(fields=['transaction_type'], name='pricing_gif_transac_11e672_idx'),
        ),
        migrations.AddIndex(
            model_name='giftcardtransaction',
            index=models.Index(fields=['order_id'], name='pricing_gif_order_i_20ad7f_idx'),
        ),
        migrations.AddIndex(
            model_name='pricelist',
            index=models.Index(fields=['code'], name='pricing_pri_code_a8d88b_idx'),
        ),
        migrations.AddIndex(
            model_name='pricelist',
            index=models.Index(fields=['is_active', 'is_public'], name='pricing_pri_is_acti_99e28c_idx'),
        ),
        migrations.AddIndex(
            model_name='pricelist',
            index=models.Index(fields=['priority'], name='pricing_pri_priorit_71e4d1_idx'),
        ),
        migrations.AddIndex(
            model_name='pricelistcustomergroup',
            index=models.Index(fields=['customer_group'], name='pricing_pri_custome_e94e49_idx'),
        ),
        migrations.AddIndex(
            model_name='pricelistcustomergroup',
            index=models.Index(fields=['customer'], name='pricing_pri_custome_2b6715_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='pricelistcustomergroup',
            unique_together={('price_list', 'customer'), ('price_list', 'customer_group')},
        ),
        migrations.AddIndex(
            model_name='pricelistentry',
            index=models.Index(fields=['price_list', 'variant'], name='pricing_pri_price_l_44fe8b_idx'),
        ),
        migrations.AddIndex(
            model_name='pricelistentry',
            index=models.Index(fields=['price_list', 'product'], name='pricing_pri_price_l_ade8e5_idx'),
        ),
        migrations.AddIndex(
            model_name='pricelistentry',
            index=models.Index(fields=['price_list', 'category'], name='pricing_pri_price_l_47cb98_idx'),
        ),
        migrations.AddIndex(
            model_name='pricelistentry',
            index=models.Index(fields=['is_active'], name='pricing_pri_is_acti_5eb367_idx'),
        ),
        migrations.AddIndex(
            model_name='taxrate',
            index=models.Index(fields=['tax_zone', 'tax_category'], name='pricing_tax_tax_zon_0761da_idx'),
        ),
        migrations.AddIndex(
            model_name='taxrate',
            index=models.Index(fields=['is_active'], name='pricing_tax_is_acti_10aae6_idx'),
        ),
        migrations.AddIndex(
            model_name='taxrate',
            index=models.Index(fields=['rate'], name='pricing_tax_rate_e700fa_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='taxrate',
            unique_together={('tax_zone', 'tax_category')},
        ),
        migrations.AddIndex(
            model_name='volumepricingtier',
            index=models.Index(fields=['variant', 'is_active'], name='pricing_vol_variant_c2c339_idx'),
        ),
        migrations.AddIndex(
            model_name='volumepricingtier',
            index=models.Index(fields=['customer_group'], name='pricing_vol_custome_0ba6bd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='volumepricingtier',
            unique_together={('variant', 'customer_group', 'min_quantity')},
        ),
    ]
