# Generated by Django 5.2 on 2026-07-28 12:11

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0004_bundleoffer_bundleofferitem_bundleorderledger_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='automaticdiscount',
            name='attributed_partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='automatic_discounts', to='pricing.promotionpartner', verbose_name='Attributed Partner'),
        ),
        migrations.AddField(
            model_name='automaticdiscount',
            name='eligible_cities',
            field=models.JSONField(blank=True, default=list, verbose_name='Eligible Cities'),
        ),
        migrations.AddField(
            model_name='automaticdiscount',
            name='eligible_countries',
            field=models.JSONField(blank=True, default=list, verbose_name='Eligible Countries'),
        ),
        migrations.AddField(
            model_name='automaticdiscount',
            name='eligible_states',
            field=models.JSONField(blank=True, default=list, verbose_name='Eligible States'),
        ),
        migrations.AddField(
            model_name='automaticdiscount',
            name='total_stack_cap_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maximum combined savings allowed when this automatic discount stacks.', max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Total Stack Cap Amount'),
        ),
        migrations.AddField(
            model_name='discountcode',
            name='attributed_partner',
            field=models.ForeignKey(blank=True, help_text='Optional influencer, affiliate, or campaign source credited for this code.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discount_codes', to='pricing.promotionpartner', verbose_name='Attributed Partner'),
        ),
        migrations.AddField(
            model_name='discountcode',
            name='eligible_cities',
            field=models.JSONField(blank=True, default=list, help_text='Optional city filters for this code.', verbose_name='Eligible Cities'),
        ),
        migrations.AddField(
            model_name='discountcode',
            name='eligible_countries',
            field=models.JSONField(blank=True, default=list, help_text='Optional ISO country codes that can use this code.', verbose_name='Eligible Countries'),
        ),
        migrations.AddField(
            model_name='discountcode',
            name='eligible_states',
            field=models.JSONField(blank=True, default=list, help_text='Optional state or region filters for this code.', verbose_name='Eligible States'),
        ),
        migrations.AddField(
            model_name='discountcode',
            name='total_stack_cap_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maximum combined savings allowed when this code stacks with other promotions.', max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Total Stack Cap Amount'),
        ),
    ]
