# Generated by Django 5.2 on 2026-08-25 06:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0006_repair_missing_partner_targeting_columns'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashsale',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_flash_sales', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='giftcard',
            name='issued_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='issued_gift_cards', to=settings.AUTH_USER_MODEL, verbose_name='Issued By (Staff)'),
        ),
    ]
